### ISSUE TITLE
Docs：Document language i18n

### ISSUE THREAD

**Issue by hehehai** [mswjs/msw#120]
**Document language i18n**
- Support Chinese

**Describe the solution you'd like**
Set the current document to support multi-language switching
or
Use the new document to set up an independent msw document website

**Comment by kettanaito** [comment]
Hey, @hehehai. That's a good idea. I'd like to have a multi-language support in MSW docs. I've been working on the website for this library for some time now. It will include the self-hosted docs, so the plan it to migrate from GitBook eventually. There's also quite a rewrite of docs going on, so they are much more coherent and easier to navigate. Once that is done, and the website is released, we can work on multi-language support.

I've got only one concern that I don't have resources to maintain a documentation in Chinese, as I don't write not speak that language. May I kindly ask for your help in that?

**Comment by hehehai** [comment]
@kettanaito Of course, I will prepare Chinese documents in the near future, so that when your document website is online, you can support multiple languages as soon as possible

**Comment by kettanaito** [comment]
@hehehai, that would be amazing! Please, if I may, don't translate the [current docs](https://redd.gitbook.io/msw/) just yet. It's going to change a little, so I wouldn't want to waste your time translating those parts.

I'll leave this issue open until the website is released, so we could track progress. Sounds good?

**Comment by hehehai** [comment]
@kettanaito Awesome

**Comment by kettanaito** [comment]
Hey! We have officially released the [website](https://mswjs.io) and [revamped documentation](https://mswjs.io/docs)! There is, however, no integrated multi-language support as of now. It can be added as a feature to the [website's repo](https://github.com/mswjs/mswjs.io). I'm concerned about our effort on this matter, as since MSW is not yet in a stable release, it may contain an overhead in translating a potentially deprecated/changed API to another languages.

I'm closing this, as it's not related to the library's package. I'm happy to discuss multi-language support in the aforementioned website's repo! Thank you for bringing this up.
