### ISSUE TITLE
Custom Host e.g. localhost.enterprise.com (HTTPS)

### ISSUE THREAD

**Issue by helloworldless** [mswjs/msw#147]
I'm using msw 0.15.7 with create-react-app using a custom HOST (via an environment variable), e.g. HOST=localhost.myenterprise.com. This causes the issue below. If I remove the host environment variable and just go with plain old localhost:3000, everything works fine. Can using a custom host be supported?

```text
Unhandled Rejection (TypeError): Cannot read property 'addEventListener' of undefined:
(anonymous function)
<omitted>/node_modules/msw/lib/esm/index.js:1791
(anonymous function)
<omitted>/node_modules/msw/lib/esm/index.js:51
__awaiter
<omitted>/node_modules/msw/lib/esm/index.js:31
start
<omitted>/node_modules/msw/lib/esm/index.js:1789

Module../src/mocks.js
> 26 | start();
```

**Comment by kettanaito** [comment]
Hey, @paltamadura, thanks for reporting this.

I have a guess of why this may be happening. Please, give me some time to investigate and find a proper solution. I'll keep this thread updated so you know the investigation's status.

**Comment by kettanaito** [comment]
I've tried to reproduce this issue and was successful. The first thing I've noticed, is that when running under a custom hostname, the `navigator.serviceWorker` is `undefined`. This is the technical reason behind the exception you've attached.

However, the actual reason for the issue is that Service Workers can only be run over a _secure connection_ (`localhost` is whitelisted).

## Solutions

### (Option 1) Use HTTPS for development

**Recommended**. If you establish your local server using HTTPS, it will be considered secure by the browser, allowing you to register Service Workers.

- [Using HTTPS in development (Create React App)](https://create-react-app.dev/docs/using-https-in-development/)

> To use HTTPs you would need to have an SSL certificate. You can [generate a self-signed certificate](https://stackoverflow.com/questions/10175812/how-to-create-a-self-signed-certificate-with-openssl) for development, or reuse your existing certificate, if any.

### (Option 2) Whitelist insecure host

Be cautious with this option. It implies whitelisting your custom host so that browser considers it secure. **Do not whitelist hosts you don't know**.

1. Open the Chrome flags, and navigate to the "**Insecure origins treated as secure**" (chrome://flags/#unsafely-treat-insecure-origin-as-secure) setting.
1. Mark the setting as "Enabled".
1. Put the full URL of your custom hostname (`http://localhost.myenterprise.com:3000`) in the textarea below.
1. Click "Relaunch" at the bottom of the page to restart the browser.

---

There is nothing I can do on to handle this on the library's side, as this issue comes from the Service Worker's behavior per specification.

Please let me know which option you've chosen, and whether it helped. Thanks.

**Comment by helloworldless** [comment]
Thanks! I'll have a look on Monday when enterprise things happens 😏

**Comment by kettanaito** [comment]
Glad to help. I'll use this ticket as an opportunity to provide a better error message when this situation happens. A guidance like "Service Workers are not supported, or you are using a custom hostname" may be helpful for the user.

**Comment by kettanaito** [comment]
The library will now print a meaningful error message into browser's console when such situations happen (https://github.com/mswjs/msw/commit/1d30ff956de8c62d8b1c671b5350bb8d397809e9). Will be available in the next release. 

Thank you once more for raising this.

**Comment by kettanaito** [comment]
Version [`0.15.8`](https://github.com/mswjs/msw/releases/tag/v0.15.8) now ships with an error message when `navigator.serviceWorker` is not defined.

**Comment by ghost** [comment]
@kettanaito 
> (Option 1) Use HTTPS for development

Is this sufficient? Running `worker.start()` in Chrome 91 on https://localhost:4402 with an automatically generated cert by webpack-dev-server makes the below error appear:
```
index.js:665 Uncaught (in promise) Error: [MSW] Failed to register a Service Worker:

Failed to register a ServiceWorker for scope ('https://localhost:4402/') with script ('https://localhost:4402/mockServiceWorker.js'): An SSL certificate error occurred when fetching the script.
    at index.js:665
    at Generator.next (<anonymous>)
    at fulfilled (RequestHandler-deps.js:33)
```

There are lots of solutions here: https://stackoverflow.com/questions/38728176/can-you-use-a-service-worker-with-a-self-signed-certificate

But all of them make the user start Chrome with a custom flag, none of them "just work".

**Comment by kettanaito** [comment]
@3nuc, what I've tried in the past is to configure Chrome flags (chrome://flags) to enable the following flag:

```
Allow invalid certificates for resources loaded from localhost.
Allows requests to localhost over HTTPS even when an invalid certificate is presented. – Mac, Windows, Linux, Chrome OS, Android

#allow-insecure-localhost
```

This forces Chrome to trust insecure certificates, such as self-signed certificates. 

Another alternative I've tried is adding the self-signed certificate to your keychain, if you're using MacOS. This will make Chrome trust the certificate automatically (at least it used to 6 months ago). 

Unfortunately, there's not much we can do on the library's side. What you're battling through is enabling a service worker with a self-signed certificate. Once you find a solution, you'll get your setup working without extra actions necessary on the library's side. I hope you find a suitable solution.
