### ISSUE TITLE
angular jest

### ISSUE THREAD

**Issue by manishiitg** [mswjs/msw#281]
## Environment

| Name | Version |
| ---- | ------- |
| msw  | 0.19.5   |
| node | 14.x    |
| OS   | windows wsl 2.0    |

i am facing this same issue

https://github.com/mswjs/msw/issues/273

but i am unable to install the latest node-request-interceptor for the fix

i have installed 
npm i msw --save
npm i node-request-interceptor --save

and then when i see version of interceptor of mws, it always takes the old version
```
manish@manishlenovo:~/Recruit-2.0$ npm list node-request-interceptor
recruitment@1.0.1 /home/manish/Recruit-2.0
├─┬ msw@0.19.5
│ └── node-request-interceptor@0.2.6
└── node-request-interceptor@0.3.2
```

i am doing something wrong? stuck on this. 

thanks for the help

**Comment by kettanaito** [comment]
Hey, @manishiitg. Thanks for asking this, I'll try to help you below.

Since the latest and the dependent versions of `node-request-interceptor` differ, and the range specified in the `msw` dependencies list cannot be satisfied with the latest version (`0.2.x` doesn't match `0.3.x` in SemVer), it installs the latest version alongside the old one. This will not result into `msw` package using the latest version, even if installed explicitly.

What I can recommend to test the latest state of the `msw` is to perform these steps:

1. Clone the repository:

```bash
$ git clone https://github.com/mswjs/msw.git
$ cd msw
$ yarn install
```

2. Build the package:

```bash
$ yarn build
```

> Since the current version of the `msw` package in the `master` branch relies on `node-request-interceptor@0.3.x`, it will install the latest version of that package without you having to explicitly specify that.

3. Link the package locally:

```bash
$ yarn link
# Should produce a message like "msw is successfully linked"
```

4. Use the linked version of the `msw` package in your application:

```bash
$ cd ~/my/app
$ yarn link msw
```

> If you are using `npm` make sure to use `npm link` and `npm link msw` in the MSW directory and your application's directory respectively.

Please let me know if this helps and you can verify that the issue is fixed. If not, please provide as much details as possible, especially:

1. How do you perform an actual request?
1. How do your request handlers look like?

Preparing a minimal reproduction repository is the best way to get the issue fixed. So, if you have time, please prepare one, so we could look into it much more efficiently. Thanks.

**Comment by kettanaito** [comment]
The `0.20.0` version of `msw` comes with the `node-request-interceptor` dependency version bump that handles the `XMLHttpRequest` instances created by Angular properly. The issue you are experiencing should be gone.

Please let me know if it works for you after updating to `msw@0.20.0`. Thanks.

**Comment by manishiitg** [comment]
yes i can confirm that issue is fixed now . thanks
