### ISSUE TITLE
Question: can I safely use multiple versions of GraphQL in my project?

### ISSUE THREAD

**Issue by nimobeeren** [mswjs/msw#288]
I'm using Mock Service Worker on an existing stack, which depends on `graphql@^14`. The `msw` package depends on `graphql@^15`, which is not supported by one of our existing dependencies. This means we are not able to upgrade at the moment.

We've had issues in the past when dealing with multiple GraphQL versions at the same time. We would get errors like `Duplicate "graphql" modules cannot be used at the same time since different versions may have different capabilities and behavior.`

Though I haven't run into this issue with `msw`, we'd like to prevent this from happening again. We thought about rolling back to an older version of `msw` that still depends on GraphQL 14, but that would mean we lose out on features and bug fixes (the last release with GraphQL 14 was v0.13.0).

So my question is: can I safely use GraphQL 14 in my project, even though `msw` depends on GraphQL 15?

**Comment by kettanaito** [comment]
Hey, @nimobeeren. 

Mock Service Worker uses the `graphql` package to parse a request's body (or query) that contains a GraphQL operation description. Since it's you who produces that query, if you're using the previous version of GraphQL I don't see why it would fail if MSW uses the next version.

Nevertheless, I highly recommend to check the [version 15 release notes](https://github.com/graphql/graphql-js/releases/tag/v15.0.0) and see if there's anything from the breaking changes that may affect your application (i.e. a feature you were using that's been removed).

Hope this helps. Let me know how it goes.
