### ISSUE TITLE
Question: How can I prevent mockServiceWorker.js from being added to build folder?

### ISSUE THREAD

**Issue by PritamSangani** [mswjs/msw#291]
Hi. 

I have initialised the mock service worker for browser integration in my React app and is in the public folder. The file states that it shouldn't be deployed to production. 

How can I prevent the file from being added to the build when I run `npm run build`. 

Would the service worker start in the browser even though in the index file I only start the worker if the NODE_ENV is not production?

**Comment by kettanaito** [comment]
Hey, @PritamSangani.

Although you copy the `mockServiceWorker.js` file into your public directory, the Service Worker will not get registered automatically. For that you need to explicitly call `worker.start()` as a part of your application's code. 

> Would the service worker start in the browser even though in the index file I only start the worker if the NODE_ENV is not production?

No, it wouldn't. The only thing you'd have is a JavaScript file (worker script) that is not used by anything in production.

The worker script is required to be in a public directory in order to be served by your application during development. We've chosen a file copying strategy to give you a transparent control over the script itself, and to better understand where the Service Worker actually is. However, since the worker script is in the public directory, it most likely gets copied to the built version of the application as well. While this has no negative effect on its own (considered you've enabled mocking conditionally in your application's code), it still introduces an unused build file, which may get confusing.

I'm not sure what recommendation to give here. If the unused file annoys you, consider having a cleanup script that runs on CI, so you don't lose the worker script locally each time you build. If you don't mind the file itself, just make sure you are not enabling the mocking on production and you should be fine.

Let me know which solution you choose, I'm curious.

**Comment by luistak** [comment]
> consider having a cleanup script that runs on CI

Hi @kettanaito in my current app I'm following the same strategy to remove before the build it works fine 😄 

package.json scripts
```js
    "msw:cleanup": "rm public/mockServiceWorker.js",

    "prebuild:ci": "yarn msw:cleanup",
    "build:ci": "yarn build",
```

**Comment by kettanaito** [comment]
I don't think there is more to suggest in this matter, so I'm closing the issue. Please, feel free to discuss here further, I will reopen it in case we come to the conclusion this can be somehow handled as a part of the library's API, but I doubt that. Thanks!

**Comment by dellenshang** [comment]
> > consider having a cleanup script that runs on CI
> 
> Hi @kettanaito in my current app I'm following the same strategy to remove before the build it works fine 😄
> 
> package.json scripts
> 
> ```js
>     "msw:cleanup": "rm public/mockServiceWorker.js",
> 
>     "prebuild:ci": "yarn msw:cleanup",
>     "build:ci": "yarn build",
> ```

yes, i remove after the build it works so good
> ```js
> "postbuild": "rm dist/mockServiceWorker.js"
> ```

**Comment by pegiadise** [comment]
For `vue-cli@5.0.8` or similar, you can do:
```js
  chainWebpack: (config) => {
    // do not emit mockServiceWorker.js asset in production
    if (process.env.NODE_ENV === 'production') {
      config.plugin('copy').tap((opts) => {
        opts[0].patterns[0].globOptions.ignore.push('**/mockServiceWorker.js')

        return opts
      })
    }
  }
```

**Comment by ColinCee** [comment]
Ran into this issue on our CI today, the `yarn install` would automatically create `public/mockServiceWorker.js`. This caused our pipeline to fail when eslint / prettier ran.

We don't currently use the browser integration only the node integration for integration tests with react testing library.

IMO, msw really shouldn't be creating the file on install, it should be part of a manual init step. I can't imagine everyone wanting the Browser integration

**Comment by aleinin** [comment]
Here is a Vite example removing `mockServiceWorker.js` if you happen to use a specific vite config for production builds: 

(assuming your build directory is dist)

```
import { rimraf } from 'rimraf';
import { defineConfig } from 'vite';

const removeMSW = () => ({
  name: 'remove-msw',
  closeBundle: async () => {
    await rimraf(path.join(__dirname, 'dist', 'mockServiceWorker.js'));
  },
});

export default defineConfig({
  plugins: [
    removeMSW(),
  ]
}
  ```
  
  https://rollupjs.org/plugin-development/#closebundle

**Comment by md-coops** [comment]
A more secure option I use is with a NextJS app is the following;

I proxy `/mockServiceWorker.js` to another service that stores the worker script. The call for the service worker script must be made to the same host as your application so it can regester the workers sucessfully. Although, there is no reason why this same host call cannot be proxied elsewhere. 

Like many, we use 'build once deploy many' CI/CD pattern so I never ever want to bundle the script into the build as it may leak into production some day.

I have storage accounts provisioned for a couple non-prod environments where I can stricly control the network access from the browser (or NodeJS). The storage accounts hold the worker scripts, along with other MSW related content (like mock json repsonses). By using this arcitecture I can be 10x more confident that my porduciton application could never reach a generated worker script since I have no such storage accounts in prod.

Perhaps over engineerd but this is most sucrue way that I have found.

**Comment by dyljhd** [comment]
This was an issue that I faced today - with the help of a co-worker, we came up with this solution.

Creating a Vite plugin, similar to a few posts in this issue, but using the `writeBundle` method (https://rollupjs.org/plugin-development/#writebundle).

- Retrieve the `outDir` from the method, which in most cases will be `dist`.
- Resolve the path with the MSW filename, which in most cases will be `mockServiceWorker.js`.
- Delete the file (using the path created above) with `fs.unlink`, as well as handling any errors within the console.

The console will read:
```
[remove-msw]: MSW public file, at '<PATH_TO_REPO>\dist\mockServiceWorker.js' was deleted successfully
```
or
```
[remove-msw]: MSW public file, at '<PATH_TO_REPO>\dist\mockServiceWorker.js' could not be deleted
<ERROR> // whatever the error is
```

Here is the plugin code:
```
import fs from 'fs';
import path from 'path';
import { Plugin } from 'vite';

const PLUGIN_NAME = 'remove-msw';
const MSW_FILENAME = 'mockServiceWorker.js';

export function removeMSW() {
  const plugin: Plugin = {
    name: PLUGIN_NAME,
    writeBundle(outputOptions, _inputOptions) {
      const outDir = outputOptions.dir;

      if (outDir === undefined) return;

      const mswDir = path.resolve(outDir, MSW_FILENAME);

      fs.unlink(mswDir, err => {
        if (err) {
          console.log(
            `\n[${PLUGIN_NAME}]: MSW public file, at '${mswDir}' could not be deleted`,
            err
          );
          return;
        }
        console.log(
          `\n[${PLUGIN_NAME}]: MSW public file, at '${mswDir}' was deleted successfully`
        );
      });
    },
  };

  return plugin;
}
```

Hope this can help someone :)

**Comment by gynekolog** [comment]
For next.js I used separate file with mock initialisation called `start-api-mock.ts`, localized in the `src` folder:
```ts
"use client";

// You can use your own implementation, don't need to use this one.
async function initMocks() {
  if (typeof window === "undefined") {
    const { server } = await import("./tests/server");
    server.listen();
  } else {
    const { worker } = await import("./tests/browser");
    worker.start({
      onUnhandledRequest: (request, print) => {
        if (request.url.toString().startsWith("YOUR_API_URL")) {
          print.warning();
        }
      },
    });
  }
}

initMocks();

export {};
```

`next.config.js`:
```ts
...
env: {
    // Hack to omit the API mock path from the client bundle when it's not enabled.
    apiMockPath: process.env.USE_API_MOCK ? "./../start-api-mock" : "",
  },
  ...
```

`_app.tsx` (call it outside the `App` component):
```ts
// Start API mock server.
if (process.env.apiMockPath) {
  import(process.env.apiMockPath);
}
```
