### ISSUE TITLE
feature request: resolve graphql queries

### ISSUE THREAD

**Issue by benmonro** [mswjs/msw#292]
**Is your feature request related to a problem? Please describe.**
not a problem per say, just a thought.

**Describe the solution you'd like**
if i do the following: 

```js
graphql.query("GetFoo",  (req, res, ctx) => {
  return res(ctx.data({foo:"bar", baz:"qux"});
});
```

then in the app do the following query:
```gql
query GetFoo {
      foo 
    }
```

would be nice if msw would handle the gql resolutions and only return `{foo:"bar"}`.

Currently no matter what query you provide here, you will always get back `{foo:"bar", baz:"qux"}`

**Describe alternatives you've considered**
can't think of any

**Additional context**
n/a

**Comment by kettanaito** [comment]
Hey, @benmonro. That's a great question.

The current GraphQL API is operation-based and there is no actual data resolution at place. It responds with the given payload disregarding if it actually matches what you've requested in the operation, leaving this matching up to you. That is intentional in order to preserve a lightweight response logic. In order to perform actual query matching as a part of mock one would have to take multiple factors into account: fields inter-dependencies, custom scalars/decorators, and, in the end, this would resulted into you providing the entire schema to resolve a query.

That being said, we are actively discussing the option to add a schema-based GraphQL mocking (#184). The _future_ usage of such API may look like:

```js
graphql.schema('http://localhost:8080/graphql', graphqlSchema)
```

Current request handler API should be enough to create a proof of concept for such API. If you are interested, I'd love to have your contribution in this, as you are a valuable contributor. Hope this little insight helps.
