### ISSUE TITLE
typescript error on request.body.query

### ISSUE THREAD

**Issue by benmonro** [mswjs/msw#297]
## Describe the bug
When using request.body.query, i get the following typescript error:

![image](https://user-images.githubusercontent.com/399236/88567068-d40b5c80-cfeb-11ea-98c7-05b0b44cbdc5.png)

may possibly be related to https://github.com/mswjs/msw/issues/296
## Environment

- `msw: 0.19.5`
- `nodejs: 12.16.1`
- `yarn: 1.22.4`

> Please also provide your browser version.

## To Reproduce
create a graphql handler and use `req.body?.query` in typescript

## Expected behavior
no error

**Comment by kettanaito** [comment]
Hey, @benmonro. Thanks for reporting this.

That's an issue in how request body is typed in case of GraphQL. I've opened a pull request that annotates `req.body` as a nullable record that contains `query` and `variables` properties. Could you please see if the test cases for these changes look like what you're trying to do? Thanks.

**Comment by benmonro** [comment]
lgtm thanks!

**Comment by benmonro** [comment]
@kettanaito this bug is still happening for me in VSCode on 0.20.0

![image](https://user-images.githubusercontent.com/399236/88959625-256b5400-d257-11ea-9e32-3b34494c3938.png)

**Comment by kettanaito** [comment]
You have to check if `req.body` exists before passing the `query` value further.

Since you can perform a GraphQL operation via both GET and POST requests, in case of a GET request there will be no `req.body`, and the operation description will be described in the request query string. That's why `req.body` is potentially undefined.

The TypeScript error you show above originates from a third-party tool that expects a `query` of type `string | Source`. Since there's no explicit check that `req.body` exists, `query` value is potentially `undefined`.

You can use type casting if you are sure that your GraphQL operation has a request body:

```js
const query = req.body?.query as string
```

Alternatively, provide type guarding:

```ts
if (req.body) {
  const { query } = req.body
}
```
