### ISSUE TITLE
Upgrade to version 0.20.1 gives: Async callback was not invoked within the 5000ms

### ISSUE THREAD

**Issue by julianklumpers** [mswjs/msw#317]
## Describe the bug
I'm not really sure if this a real bug, but i feel its worth mentioning.

in version 0.19.5 i made all my api mocks with `msw` which worked great. i setup the server in `setupTests.js` in a CRA application like this:
(note the implicit function call)
```js
import { server } from 'mocks/server/server'

beforeAll(server.listen)
afterEach(server.resetHandlers)
afterAll(server.close)
```

After upgrading. to version 0.20.1 all my tests which uses api mocks were failing with the following error: `Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Error:`

It took me a while to figure out what happend, but the following solved the problem for me.
The done parameter from the before and after callback was passed implicit to server.x

```js
import { server } from 'mocks/server/server'

beforeAll(() => {
  server.listen()
})
afterEach(() => {
  server.resetHandlers()
})
afterAll(() => {
  server.close()
})
```

## Environment

- `msw: 0.20.1`
- `nodejs: 10.17.0`
- `npm: 6.11.3`
- `Chrome 84.x`

## To Reproduce

1. in setupTests.js. notice the implicit function call. this Implicit passes the `done` parameter
```js
import { server } from 'mocks/server/server'

beforeAll(server.listen)
afterEach(server.resetHandlers)
afterAll(server.close)
```

## Expected behavior
it works as in previous versions if there are no breaking changes notes.

**Comment by kettanaito** [comment]
Hey, @julianklumpers. Thanks for reaching out with this.

We never encouraged to pass the `server.*` functions as a shorthand to test frameworks hooks, since those hooks, as you've noticed, may rely on the async execution via the `done` callback. Please always provide an anonymous function that invokes respective library methods:

```js
beforeAll(() => server.listen())
afterEach(() => server.resetHandlers())
afterAll(() => server.close())
```

> This also ensures better backwards-compatibility if any of the mentioned methods start returning `Promise` in the future.

I understand the notion to shorten this syntax, but there is no practical use in doing so. Shorthand functions sometimes won't work, as they implicitly propagate the parent function's arguments and may cause all sorts of strange behavior. 

The technical reason why it stopped working with the `0.20.0` release is because `server.listen()` now accepts an options object where you can [react to unhandled requests](https://mswjs.io/docs/api/setup-server/listen#onunhandledrequest). That's why it accepts the `done` callback and your test runner never sees that callback invoked within the timeout period.

Since we are below `1.0`, any minor version may contain breaking changes, which is a valid behavior per SemVer. I hope this info helps.
