### ISSUE TITLE
next example not using 'require'

### ISSUE THREAD

**Issue by benmonro** [mswjs/msw#359]
**Is your feature request related to a problem? Please describe.**
We are using next js w/ msw.  In the example posted here: https://github.com/vercel/next.js/blob/canary/examples/with-msw/pages/_app.js#L1

a `require()` is done which adds msw to the bundle.  We are using a lot of big json files for fixture data in conjunction w/ our msw endoints.  And the use of require here is causing our bundle size to balloon.  

**Describe the solution you'd like**
Looking for a way to safely load msw before any react renders that doesn't use require.  

**Describe alternatives you've considered**
await import() but that seems to cause race conditions where msw doesn't load in time (i.e. before react tries to fetch)

**Additional context**

**Comment by kettanaito** [comment]
Hey, @benmonro. 

That `require` statement is called if your `NEXT_PUBLIC_API_MOCKING` environmental variable is set to `enabled`. In that case it's the expected behavior to import and bundle `msw` into your app (a development scenario). Double check that value of the `NEXT_PUBLIC_API_MOCKING` environmental variable in your `.env` and `.env.*` files.

**Comment by kettanaito** [comment]
Hey, @benmonro. Did you have a chance to double check the usage? Please let us know.

**Comment by benmonro** [comment]
Yeah we need to use it in production so wet came up with our own solution but it would still be nicer to have an official one

**Comment by kettanaito** [comment]
I confirm that the [Official NextJS usage example](https://github.com/vercel/next.js/tree/canary/examples/with-msw) does not include `msw` package in its production bundle. See the bundle analyzer screenshot below.

- `with-msw` state as of https://github.com/vercel/next.js/commit/746000ea5e55c12763defe01028d03ae765eda67 commit
- `msw@0.20.x`

<img width="1196" alt="Screen Shot 2020-09-11 at 09 46 50" src="https://user-images.githubusercontent.com/14984911/92886349-ddbe1780-f413-11ea-97b8-9a7bf5f0149c.png">

> **Note:** You have to set the `NEXT_PUBLIC_API_MOCKING` environmental variable to `"disabled"` in your `.env` file, otherwise you are bundling a production app with the mocking enabled, which intentionally includes `msw` in the build.

If you have a custom build setup make sure you are importing `msw` conditionally so it doesn't end up in the production bundle unused. If you want to run `msw` in production intentionally it must be included by design in order to run.

**Comment by ghost** [comment]
> I confirm that the [Official NextJS usage example](https://github.com/vercel/next.js/tree/canary/examples/with-msw) does not include `msw` package in its production bundle. See the bundle analyzer screenshot below.

@kettanaito There seems to have been a regression in the next.js build process as now msw _is_ being included in the bundle. I've opened an issue for it with next.js here: https://github.com/vercel/next.js/issues/25607 (note that I tested this by removing .env.production from the example, as otherwise you _would_ expect msw to be present in the bundle, since `NEXT_PUBLIC_API_MOCKING` would be `enabled`). See the linked issue for more details.
