### ISSUE TITLE
Generate API responses from swagger doc

### ISSUE THREAD

**Issue by sahanatroam** [mswjs/msw#394]
**Is your feature request related to a problem? Please describe.**
the API responses can easily get out of sync when hardcoded. 

**Describe the solution you'd like**
A simple way to use the swagger doc to generate the JSON API responses

**Comment by kettanaito** [comment]
Hey, @sahanatroam. Let me say that I'm not experienced with Swagger, so what I will be saying may be incorrect.

Partially, the hard-coding of responses in the mocks is intended. When you derive your mocks from an external input (i.e. an API spec) you're delegating the source of truth that that input. While this may be what you want, you need to account for the breaking changes in the input that are going to implicitly leak into your mocking layer, causing the issues with implementation. For example, if a certain endpoint starts to return a different shape of a JSON response.

That is where having the mocked responses living in the mocking layer provides a sustainability and a way to reason about API changes over time. As in "hey, see my mocks from the API state a week ago, and see your current spec". This can also be covered by API spec versioning and generating mocks from a specific version.

Another aspect of API specification documents is that they are rather an abstract specification of an API, not necessarily allowing to derive request handlers from them. For example, what if a response doesn't have an example in the Swagger? 

I would like to discuss this topic more thoroughly, specifically:

- How would such API look on the library's side? (take into account that it runs in the browser)
- When should Swagger be transformed into request handlers? (take into account that it most likely implies Swagger parsing and evaluation due to refs)
- How to handle multi-example scenario on a single path?
- How to handle a scenario when there's no example for a path?

---

If you wish to derive your mocking from the actual server responses I highly recommend using _the traffic_ for that purpose. Tools like [`tapico-msw-webarchive`](https://github.com/Tapico/tapico-msw-webarchive) can transform an HAR file into a list of request handlers to use with MSW.

**Comment by kettanaito** [comment]
While this is a practical feature, it falls out of the library's main scope and should be addressed in a separate NPM package. If you develop such package, feel free to mention it here so we could recommend it to other users or potentially include it in the MSW organization. Thank you.

**Comment by cwilso03** [comment]
While it may be best as a separate NPM package, for context, a set of generated JSON API responses would be great for client-side testing, where the API back-end has an up-to-date Swagger/OpenAPI spec.

In my case, my API server is using the _TSOA_ package (https://github.com/lukeautry/tsoa), which generates (via a file watcher in my IDE) the OpenAPI v3 spec document which matches the implementation.  With that spec, another file watcher uses (strange name, I know) _oazaptfs!_ (https://github.com/cellular/oazapfts) to generate a React client library to use in the web client.  

My React client uses _Jest_ and _React Testing Library_ (https://github.com/testing-library/react-testing-library) to do automated testing of the React components.  React Testing Library is able to use _Mock Service Worker_ for API mocks (see https://testing-library.com/docs/react-testing-library/example-intro).  It would be awesome to be able to use that same OpenAPI spec document to also generate the example JSON responses for MSW to use in these tests. 

In this use case, I'm treating the OpenAPI spec as the source of truth, and want to know if anything breaks as the API changes, especially if it's because the API is returning a "different shape of a JSON response."  Most of the time, the generated React client library catches changes, since it is generated in TypeScript, to match the types established in the TSOA-based API server.  But the test cases leveraging MSW are one area that don't currently have that consistency, because the JSON responses are hard-coded.

I fully agree that the valid uses for MSW are broader than this specific use case; I just wanted to throw some context in since there was the "needs:discussion" label on this issue.

FWIW, I stumbled across this issue report because I was exploring whether I could further leverage the OpenAPI spec in my test case generation as well.

**Comment by kettanaito** [comment]
>  It would be awesome to be able to use that same OpenAPI spec document to also generate the example JSON responses for MSW to use in these tests.

I believe nothing prevents you from doing just that: use any suitable tool to generate JSON fixtures based on your OpenAPI document and use those fixtures with MSW:

```js
import pets from './fixtures/pets.json'

rest.get('/pets', (req res, ctx) => {
  return res(ctx.json(pets))
})
```

You may as well design a custom mapping between a response example and a handler to make things more automated. I agree that this would require you to write this set up manually, but it's a viable option until we provide a recommended solution.

**Comment by cwilso03** [comment]
Yep, I completely agree.

**Comment by zeorin** [comment]
FYI: https://github.com/zoubingwu/msw-auto-mock
