### ISSUE TITLE
Can I use mock-service-worker for test project?

### ISSUE THREAD

**Issue by zaharzagrava** [mswjs/msw#415]
Hi! Can I use this package for a test portfolio project that I can showcase on my test portfolio project?

The docs say that: "_It's not recommended to include Mock Service Worker in production. Doing so may lead to a distorted experience for your users._" I am not sure what is meant here by distorted experience, so that's why I am asking.

Thank you for your time and for creating this package :)

**Comment by marcosvega91** [comment]
Hi @zaharzagrava thanks for reaching us 😄 .

I think that for a test portfolio will be not a problem. Is not recommended to use MSW in production because users could have real APIs instead of MSW. So it's like don't forgot to disable in production otherwise instead of receiving data from real APIs you will receive data from mocks. Hope to be clear 💯

**Comment by kettanaito** [comment]
Yes, you can.

If you plan to use MSW instead of an actual backend. Bear in mind it will be your responsibility to update and maintain the worker in production, if necessary.
