### ISSUE TITLE
Why are query parameters removed from matchers?

### ISSUE THREAD

**Issue by phishy** [mswjs/msw#443]
Is it an architecture thing that we can’t use search parameters as matchers? Why are they removed?

**Comment by kettanaito** [comment]
Hey, @phishy. Thanks for reaching out with a question.

Query parameters are stripped off of the request handler URL by design. You may still specify them, but you will be warned that doing so doesn't affect the matching at all, and advised to remove them from your request handler URL.

From the REST API perspective, query parameters do not describe a resource path, but rather provide an additional information to the resource. Request handlers must provide a resource path (absolute, relative, with parameters, or using RegExp). In a traditional routing query parameters are not included in the path on a server, nether should they be in your request handlers (that represent a server). 

You can still access query parameters to build your mocking around them, as they are exposed in the `req.url.searchParams` interface. See the [Query parameters](https://mswjs.io/docs/recipes/query-parameters) page for more information and usage examples. 

If you feel this response or documentation not covering your question sufficiently, please post a follow up information in this thread. Thanks.

**Comment by phishy** [comment]
I totally understand. But there are more APIs out there that are not fully REST compliant than there are that are. Thanks for answering the question. It's just a surprising move  for such an awesome tool to leave out a large swatch of developers working with non REST-compliant APIs. Working with query parameters programmatically inside the matcher has worse ergonomics that using it as a matcher itself. Maybe I can fork it. Thanks!

**Comment by kettanaito** [comment]
You can always build a [custom request handler](https://mswjs.io/docs/recipes/custom-request-handler) to work with a non REST-compliant APIs. That would give you the desired ergonomics without having to clone and modify things (which you are totally free to do).

Including query parameters in the path itself isn't the best idea, as parameters are order- and quantity-sensitive. You'd have to parse them to match a request reliably. Parsing is already done as a part of MSW (`req.url`), so I'd suggest to utilize that, instead of creating a workaround of any sort.

The best part is that you can open source your custom handlers and let others use them as well. Our goal as library maintainers' is to expose a minimal yet versatile API to the consumers. Perhaps there'll be a community-driven hub of handlers in the future. I'd like to see that.

**Comment by phishy** [comment]
I can’t change the API. It requires query parameters in order to work. I’m
not sure what you’re saying to utilize.

**Comment by kettanaito** [comment]
Please see the [custom request handler](https://mswjs.io/docs/recipes/custom-request-handler) recipe for more details. You can create a request handler like `rest.*` that would take query parameters into account when matching requests.

**Comment by phishy** [comment]
Thank you! Great work!
