### ISSUE TITLE
Add a debugging request handler

### ISSUE THREAD

**Issue by kettanaito** [mswjs/msw#453]
**Is your feature request related to a problem? Please describe.**

One of the most common issues developers experience is unmatched requests.

**Describe the solution you'd like**
I suggest to add a debugger request handler (i.e. `log`) that would act as a transparent handler, meaning it would log out any requests that didn't match preceding handlers.

**Describe alternatives you've considered**
We usually suggest to do that manually, but neither of the existing handlers can be fully used as a transparent request handler, as they have a predicate built-in which limits requests captured to a certain degree.

**Comment by kettanaito** [comment]
The documentation now includes the [Debubugging uncaught requests](https://mswjs.io/docs/recipes/debugging-uncaught-requests) recipe that's highly recommended to follow whenever encountered a situation when a request is not mocked when it should have been.

**Comment by Aprillion** [comment]
I would vote for a default behaviour `onUnhandledRequest: "warn"` instead of bypass 😄 

my thinking is that when introducing MSW with a `start()` or `listen()` in a project:
* if all API requests explicitly fail by default, I can spot that there is some problem and either modify my settings or make handlers for all missing APIs
* if all works at this step and I only mock some APIs while keeping the bypass, I will be surprised at some random point in the future

**Comment by timdeschryver** [comment]
How would the debug handler behave different from `onUnhandledRequest: "warn"`?
Currently, I would agree with @Aprillion and set the default to `warn`. 
I think in most of the cases, when MSW is introduced to a project, it's the intention to mock all the API requests, so warning about unhandled requests seems like the option that helps the most with this transition.

**Comment by kettanaito** [comment]
> I think in most of the cases, when MSW is introduced to a project, it's the intention to mock all the API requests

What about the mock-driven development? Although unexplored, I find it a promising direction and can see people developing against MSW until their backends are ready. Wouldn't seeing a bunch of warnings be annoying? 

I do share the idea to set "warn" as the default unhandled request policy, it'd ease the debugging curve for people experiencing uncaught requests. I just wish for us to think through all the implications of that change.

**Comment by Aprillion** [comment]
If we are not able to tell which default makes more sense for some vast majority of users, then perhaps in version v1.0.0 this config should be required without a default value, to force users to think about the setting for a few seconds 🤔

(the README and tutorial examples could include `warn` for people who only copy-paste the "hello, world" example + a special section about mock-driven development)

**Comment by timdeschryver** [comment]
That's a good point @kettanaito .
Making the option required might make it slightly harder to get started with MSW?

What would be the difference between `warn` and the new proposed handler? 
I haven't experienced this issue yet, but think I'll have to test this out on my own because I'm thinking that `warn` would resolve these issues (and I'm probably wrong about this).

Would it help if we print all the active handlers when MSW is bootstrapped?
Similar to react/angular/vue that log `Angular Live Development Server is listening on localhost:4200` when the application is ready.

**Comment by kettanaito** [comment]
I'm _so_ leaning forward to making `onUnhandledRequest: 'warn'` to be the default behavior. My only concern is that when I add MSW to an existing project, I'll see a million warnings on the page in a browser. That default is sure nice for testing, where you don't wish to have unhandled requests, but I'm still unsure if the browser-first approach wouldn't suffer from such default.

> Making the option required might make it slightly harder to get started with MSW?

My bad, I didn't mean to make it required. 

> What would be the difference between warn and the new proposed handler?

A good point. The main difference would be that you're in control of when that `log` handler is called. You can place it between handlers and inspect how they communicate, for examples like these:

https://github.com/mswjs/msw/blob/b17a6d4f32d1d5b8782039849de6d4dfe66d89b7/test/rest-api/redirect.mocks.ts#L4-L14

```js
rest.get('/books', (req, res, ctx) => {
  // Hits the "GET /user" request handler below.
  const res = await fetch('/user')
}),
rest.get('/user', (req, res, ctx) => {...})
```

But I don't believe this use case is the main concern of our users at the moment. A huge amount of issues come from people not matching requests correctly, where the defaults of `onUnhandledRequest` may help.

> Would it help if we print all the active handlers when MSW is bootstrapped?

An interesting idea. We can call `worker.printHandlers()` within the activation console group message here:

https://github.com/mswjs/msw/blob/b17a6d4f32d1d5b8782039849de6d4dfe66d89b7/src/setupWorker/start/utils/activateMocking.ts#L11-L21

@Aprillion, what do you think about including the list of currently active handlers as suggested above?

**Comment by Aprillion** [comment]
Hmm, if I imagine that I believe that some request is handled, but there is a typo, printing them wouldn't help, because if I didn't notice the typo in code, I might not notice it in the console either..

If it was all done by magic, the best place to look would be browser network tab (or some similar tool for spying on Node tests).. short of that, console warn is the next best thing in that scenario.

I agree default warn would not be so nice for scenarios where people would expect a bypass.

Hmm, what about a new option that will be also the nrw default, `onUnhandledRequest: 'http418' `, that would print console error about unmatched reqest in Node, while responding with a real HTTP 418 I'm a teapot response in the browser with some response header or body to explain this is unhandled response from MSW and that it can be set up to bypass?? (so, no polution in console but a good SEO opportunity for people to search for "msw 418" to find the correct place in docs to explain it)

..does not have to be 418, I am just on phone and didn't search for more suitable code..

**Comment by kettanaito** [comment]
I believe there are multiple strategies the users may be choosing when installing MSW:

- Mock-first, no backend at all, develop entirely against MSW. Here I don't want any unhandled requests to happen.
- Incremental, there's an existing app, there's a backend, let's use MSW to either extend that backend or mock a third-party service. Here I'd expect my unhandled requests to happen, so there are no distractions to my flow.
- Testing. I've got an app, I need to write some tests in Node.js. Here I don't want any unhandled requests to happen.

From the use-cases, I see the default `onUnhandledRequest` option would be beneficial to most of them. That being said, it'd be nice to see how many people follow each of those strategies to evaluate our choice. 

The fact that misconfigured request URLs cause 80% of mismatch issuses is a **huge reason** to set `onUnhandledRequest: "warn"`. That'd be both non-invasive, but informative.
