### ISSUE TITLE
Request not intercepted when server started in start script

### ISSUE THREAD

**Issue by iperzic** [mswjs/msw#464]
## Environment

| Name | Version |
| ---- | ------- |
| msw  | 0.22.0   |
| node | v12.14.0     |
| OS   | 10.15.7 (Catalina)     |

### Background
We are trying to mock API calls when running behavioral tests with mocked API through webdriverio. 
First, we encountered an issue that wdio would hang forever and no test would get executed when starting MSW server in wdio config file. We thought that this was due to the fact that wdio and serving the app have been ran as separate node processes, but upon changing the configuration so that app is built, and served through express server, this issue is present.

Moving to client mocking is not an option for us, because some API calls are being made before React app has been bootstrapped, and we'd need to mock those requests as well.

**NOTE:** The full example project, which is essentially ejected CRA + msw installed, can be found in [this repo](https://github.com/iperzic/test-msw) 

## Request handlers

```js
const { rest } = require('msw');
const { setupServer } = require('msw/node');

const server = setupServer(
  rest.get('http://localhost:3000/test', (req, res, ctx) => {
    console.log('hit');
    return res(ctx.status(404));
  })
);

server.listen()
```

## Actual request

```js
fetch('/test')
```

## Current behavior

The server responds with 200 status code, and no unhandled requests are logged. Nothing is logged as a matter of fact, except usual CRA stuff.

The same behavior can be seen when building an app, and then serving the production version via an express server.
## Expected behavior

The mocks should catch the requests coming from the app.

**Comment by iperzic** [comment]
I have realized my understanding of how this works has been wrong, as the requests are being performed from the actual browser, while MSW is hooking into serving process. 

Closing, sorry for the confusion!

**Comment by kettanaito** [comment]
Hey, @iperzic. I'm glad you've figured it out. Nevertheless, let me double check that we are on the same page.

You can use `setupServer` API to intercept requests in NodeJS. That can be any NodeJS process: an Express app, a WebDriver runner, or a test runner (i.e. jest). If your setup performs requests in NodeJS, that's your API of choice.

You can also use `setupWorker` API that intercepts requests in a browser. You usually add that API call _as a part of your app's runtime_. That's why we recommend a conditional import of the module that calls `worker.start()`. With this approach you can use WebDriver over your app with the worker setup and have requests interception within the running browser.

**Comment by iperzic** [comment]
@kettanaito sorry for the long wait.

The thing is that I was making requests from the browser environment and trying to intercept the requests in a separate NodeJS process. In this case it was a webdriver.io instance, which obviously can't tap into browser's `fetch`, and tapping into `http` or `https` node modules didn't work because no request was made from them.

Anyway, thanks for your help!

**Comment by hammidf** [comment]
@kettanaito Bumping an old thread because I have a related question, hope you don't mind. 

Is there another way to use the worker.start() without relying on the application's runtime? I'd prefer to start it as a beforeTest() hook, because we need to use these mocks outside of our local dev environment (meaning we don't need to start a local dev server)

**Comment by kettanaito** [comment]
Hey, @hammidf.

You can set the `worker` as a global runtime variable in your app when testing, and then start the worker from your test. 

```js
// src/app.js
if (process.env.NODE_ENV === 'test') {
  const { worker } = require('./worker')
  window.worker = worker
}
```

```js
// test/Login.test.js
beforeAll(async () => {
  await getWindow().worker.start()
})
```

> `getWindow()` is your way to access the `window`, as it's different depending on which testing framework you're using. In Cypress that'd be `cy.window(cb)`, for example. 

Remember that `worker.start()` returns a Promise that you can await in your `beforeAll` hook.
