### ISSUE TITLE
create-react-app with homepage set causes MSW to not mock if there's no leading slash

### ISSUE THREAD

**Issue by hrgui** [mswjs/msw#484]
## Describe the bug
create-react-app with homepage set causes MSW to not mock if there's no leading slash

## Environment

- `msw: 0.22.3`
- `nodejs: 14.15.1`
- `yarn: 1.22.10`
- Chrome  87.0.4280.67

## To Reproduce
1. Clone https://github.com/hrgui/imaginary-dog-store
2. `yarn` to install deps, `yarn start`. 
3. `yarn start` will open up http://localhost:3000/imaginary-dog-store
4. In another tab, go to http://localhost:3000/imaginary-dog-store/

## Expected behavior
Both http://localhost:3000/imaginary-dog-store and http://localhost:3000/imaginary-dog-store/ both do the same behavior - MSW mocks in both cases

## Actual behavior
Going to http://localhost:3000/imaginary-dog-store, MSW is not intercepting any calls

**Comment by kettanaito** [comment]
Hey, @hrgui. Thank you for reaching out. 

Trailing slash sensitivity appears to be a [Service Worker behavior](https://github.com/w3c/ServiceWorker/issues/1272#issuecomment-364445866), but also a larger discussion that `/imaginary-dog-store` and `/imaginary-dog-store/` are two _different_ URLs.  Create React App rightfully sets the public URL to `/imaginary-dog-store/`, aliasing the `/public/` directory on your local machine. Although the worker does register and activates when you visit the page without a trailing slash, it doesn't intercept requests, because they seem to be out of scope. 

There has been a similar issue, where the suggested solution was to provision a redirect from `/a` to `/a/` (https://github.com/mswjs/msw/issues/369#issuecomment-720157918):

```tsx
async function bootstrap() {
  if (window.location.pathname === process.env.PUBLIC_URL) {
    window.location.pathname = process.env.PUBLIC_URL + '/'
    return
  }

  // ...the rest of your setup
}
```

You would need this on development only, as MSW is a development tool. 

There isn't much we can do on the library's side, as this is a Service Worker behavior. In your use case, the `fetch` event of the worker doesn't even fire to let the client know there's been a request.

**Comment by hrgui** [comment]
thanks @kettanaito !
