### ISSUE TITLE
Getting a 301 error after tests have run, possibly websocket-related (msw / Apollo client / TypeScript / CRA)

### ISSUE THREAD

**Issue by dgurns** [mswjs/msw#504]
## Environment

| Name | Version |
| ---- | ------- |
| msw  | 0.24.1   |
| node | 10.15.3     |
| OS   | Mac 10.14.5    |
| @apollo/client |  3.3.0 |
| typescript | 4.1.2 |
| react-scripts | 4.0.1 |

## Request handlers

```js
import { graphql } from 'msw';
import { seedUsers } from './seedUsers';
import { seedShows } from './seedShows';

export const handlers = [
  graphql.query('GetCurrentUser', (_, res, ctx) => {
    return res(
      ctx.data({
        getCurrentUser: seedUsers['1'],
      })
    );
  }),
  graphql.query('GetShows', (_, res, ctx) => {
    return res(
      ctx.data({
        getShows: [seedShows['1'], seedShows['2']],
      })
    );
  }),
  graphql.query('GetUsersStreamingLive', (_, res, ctx) => {
    return res(
      ctx.data({
        getUsersStreamingLive: [seedUsers['1']],
      })
    );
  }),
];
```

## Actual request

An example of one of my requests:

```js
const [getShows, getShowsQuery] = useLazyQuery<QueryData>(
    GET_SHOWS,
    queryOptions
  );

  useEffect(() => {
    getShows({ variables: { minShowtime, take, skip } });
  }, [getShows, minShowtime, take, skip]);
```

**NOTE:** I am using GraphQL subscriptions on a few calls, by the way -- I suspect this might be related due to the `websocket.js` in the logs.

## Current behavior

`msw` was working great for a while, then I upgraded `msw` and `@apollo/client` to the versions above. I did not change my test code at all. Now, my tests are flakey - sometimes they pass, sometimes they don't - and almost always get the following 301 error:

(I am running tests with `TZ=UTC react-scripts test --runInBand`)

```
 PASS  src/screens/Home.test.tsx (6.762 s)
 PASS  src/App.test.tsx

Test Suites: 2 passed, 2 total
Tests:       1 skipped, 3 passed, 4 total
Snapshots:   0 total
Time:        9.718 s, estimated 12 s
Ran all test suites related to changed files.

Watch Usage
 › Press a to run all tests.
 › Press f to run only failed tests.
 › Press q to quit watch mode.
 › Press p to filter by a filename regex pattern.
 › Press t to filter by a test name regex pattern.
 › Press Enter to trigger a test run.
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: Unexpected server response: 301
    at ClientRequestOverride.req.on (/Users/dangurney/Desktop/DanStuff/Dev/gig-window/web/node_modules/jsdom/node_modules/ws/lib/websocket.js:604:7)
    at ClientRequestOverride.emit (events.js:189:13)
    at ClientRequest.<anonymous> (/Users/dangurney/Desktop/DanStuff/Dev/gig-window/web/node_modules/node-request-interceptor/src/interceptors/ClientRequest/ClientRequestOverride.ts:287:14)
    at ClientRequest.emit (events.js:189:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:556:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
    at Socket.socketOnData (_http_client.js:442:20)
    at Socket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
Emitted 'error' event at:
    at abortHandshake (/Users/dangurney/Desktop/DanStuff/Dev/gig-window/web/node_modules/jsdom/node_modules/ws/lib/websocket.js:722:15)
    at ClientRequestOverride.req.on (/Users/dangurney/Desktop/DanStuff/Dev/gig-window/web/node_modules/jsdom/node_modules/ws/lib/websocket.js:604:7)
    [... lines matching original stack trace ...]
    at addChunk (_stream_readable.js:284:12)
error Command failed with exit code 1.
```

## Expected behavior

I would expect the tests to complete successfully, as they used to before I upgraded `msw` and `@apollo/client`. The tests themselves did not change. 

I wonder if possibly `msw` is not closing open websockets between test cases?

**Comment by kettanaito** [comment]
Hey, @dgurns. Thanks for reporting this. 

We'll have a look and update this issue to let you know.

**Comment by kettanaito** [comment]
> I wonder if possibly msw is not closing open websockets between test cases?

MSW doesn't support WebSockets at the moment. The support will be added in #396 in the future.

> NOTE: I am using GraphQL subscriptions on a few calls, by the way -- I suspect this might be related due to the websocket.js in the logs.

This may be the root cause of the issue. The lack of WebSocket support implies that we don't guarantee MSW will work properly with the requests that involve WebSockets. As the first step, I'd recommend you to disable MSW for the cases when such requests happen and see if it solves the issue.

It's strange, however, that this is happening only after the version update. Can you please create a reproduction repository with this issue? That would help tremendously. Thanks.

**Comment by dgurns** [comment]
Sure. Here's the repo: https://github.com/dgurns/gig-window

Tests are in `web/`:
- https://github.com/dgurns/gig-window/blob/develop/web/src/App.test.tsx
- https://github.com/dgurns/gig-window/blob/develop/web/src/screens/Home.test.tsx

Should be able to run and see the error after a `yarn install --frozen-lockfile` and `yarn test`

I really love MSW. If there's a way to even have the websocket stuff fail silently without crashing the test, that would totally work for me.

**Comment by luanmenezes0** [comment]
any updates on this issue? I'm having the same problem on a test that doesn't involve web sockets at all, but unfortunately I have no means to reproduce because it's only happening on jenkins :( , would love to hear more about this because I'm not sure where the problem lies. Btw, thank you for the great work guys

**Comment by kettanaito** [comment]
I've just tested the [reproduction repository](https://github.com/dgurns/gig-window) with `yarn test` and I couldn't reproduce the issue.

- `msw: 0.39.1`

MSW has successfully intercepted defined GraphQL queries and returned the mocked data. The tests still fail because they are not constructed correctly (do not properly await asynchronous UI elements).
