### ISSUE TITLE
working with socket.io

### ISSUE THREAD

**Issue by johnico** [mswjs/msw#525]
Hi, I am looking for a solution to work with a socket.io  so when the test is up let's say cypress or puppeteer 
and the request from the test to the mock will also send an event to socket.io

is it mean that I can add a real socket.io code ? or need to build smth by myself? because I did not find something like that in the docs

in the end, I should receive it in the redux store

my goal is to have an Integration test with cypress or puppeteer and mock for my rest api and also for socket.
all of that is for test my app without any server or the whole ecosystem

thanks

**Comment by kettanaito** [comment]
Hey, @johnico. Thanks for reaching out.

WebSocket support is on our roadmap. In fact, it's in development at the moment (#396) and you can check it out by installing the mentioned branch locally if you're experienced in that procedure. Otherwise, you can expect WebSocket support as one of the first major features to land in the next library releases. 

> is it mean that I can add a real socket.io code ? or need to build smth by myself? because I did not find something like that in the docs

Currently, there is no WebSocket support. You can find the API examples in the aforementioned pull request to see how such support will be implemented in the future.
