### ISSUE TITLE
Provide information on GraphQL query when warning about unhandled requests

### ISSUE THREAD

**Issue by baseten** [mswjs/msw#527]
Loving using MSW so far, thank you!

When warning about an unhandled GraphQL query however, the warning only shows: `[MSW] Warning: captured a POST {GRAPH_QL_ENDPOINT} request without a corresponding request handler.`

It would be useful if this could at least contain the query name that is being run as well.

**Comment by kettanaito** [comment]
Hey, @baseten. Thank you for the kind words!

That's a great suggestion. `onUnandledRequest` callback may contain information specific to a request type, which can be associated with a request handler. I think it'd be good to move that callback logic into the handler declaration. My only concern is that if you give a custom function to `onUnhandledRequest` option it should still somehow be provided with handler information.

**Comment by baseten** [comment]
I haven't dug into the source a great deal, but could the default `onUnhandledRequest` callback determine if the `request` is a GraphQL request somehow and change the message accordingly?

https://github.com/mswjs/msw/blob/9c894760fef38f84d8fd4841a837a5ab6e1c5ec7/src/utils/request/onUnhandledRequest.ts#L23

I suppose it isn't fullproof, but if the `request.body` for a `POST` contains `operationName` and `query` then it's likely a GraphQL request and the `operationName` could be added to the warning message?

Although I can see that only `query` is actually required in the spec: https://graphql.org/learn/serving-over-http/#post-request 🤔

**Comment by kettanaito** [comment]
That would be an inversion of control that is rather undesirable in this case. When you are in a `graphql` request handler you can safely assume you're handling a GraphQL request, because the handler's predicate ensures that. So you don't have to check a request to be a valid GraphQL query again in the separate `onUnhandledRequest` function that gets called without further context. Furthermore, there isn't a reliable way to tell apart an actual GraphQL query and a seemingly compatible regular REST API request (see #489). That's to the point that the more places there are which determine that the more fragile the logic becomes. 

I think the message of `onUnhandledRequest` must be defined as a part of request handlers (`rest.*`, `graphql.*`) declared within the library. Extending the request handler object isn't an issue, but the right invocation and preservation of customization are to be discussed.

**Comment by kettanaito** [comment]
My bad, what I suggest above makes no sense: no handler would be called for an _unhandled_ request. 

You're right, it seems like a good way to go here is to determine if a request if a GraphQL operation within the `onUnhandledRequest` implementation and output a different message then. We can separate the GraphQL request predicate logic from the `graphql` request handler predicate and reuse it:

https://github.com/mswjs/msw/blob/9c894760fef38f84d8fd4841a837a5ab6e1c5ec7/src/graphql.ts#L176-L191

Perhaps we won't need all of this, or perhaps we could rework this and integrate such a newly created utility into this predicate. Would love to hear your opinion on this.

**Comment by baseten** [comment]
> My bad, what I suggest above makes no sense: no handler would be called for an unhandled request.

Indeed and determining if a POST request is a REST or GraphQL call is not simple in and of itself. This is also causing a bug for our use case as described in the linked issue.

Having a separate graphql predicate utility sounds like a good approach. 

In relation to the linked bug, perhaps this utility could also work with a similar API to `graphql.link`. Maybe optionally `server.listen` could be configured with an array of graphql endpoints and if supplied these might be the first port of call to match against a request, before attempting to parse a graphql query and match a specific handler? If the predicate utility handled both cases it might solve both issues
