### ISSUE TITLE
Error while doing response patching with GraphQL

### ISSUE THREAD

**Issue by lenoirzamboni** [mswjs/msw#547]
## Environment

| Name    | Version |
| ------- | ------- |
| msw     | 0.22.0   |
| browser | Chrome     |
| OS      | macOS     |

## Current behavior

While running on the **staging** environment, a response patching is failing due to the addition of a strange `map` header:

```
Access to fetch at 'https://api.somesite.com/graphql/' from origin 'https://staging.somesite.com' has been blocked by CORS policy: Request header field map is not allowed by Access-Control-Allow-Headers in preflight response.
```

![success_request_headers](https://user-images.githubusercontent.com/4825333/104938620-16f03080-598e-11eb-864d-025ca4eb21d0.png)

This `map` header, is literally a map containing:

![map_header_content](https://user-images.githubusercontent.com/4825333/104938035-4488aa00-598d-11eb-8717-0c8c2f2de316.png)
 
**OBS**: The response patch does not fail while running the same code on the **localhost** environment.

## Expected behavior

It should return the original data plus the appended mocked data.

## Request handlers

```js
import { graphql } from 'msw'

...

const allHistoryOrders = graphql.query(
  'someQuery',
  async (req, res, ctx) => {
    if (req.variables.something === SOME_DATA_X) {

      const originalResponse = await ctx.fetch(req)
      const originalResponseData = await originalResponse.json()

      const { data } = originalResponseData

      const newResults = data.someData.results.concat(
       someArrayData
      )
      data.someOtherData.results = newResults

      return res(ctx.data(data))
    }
  }
)

export { allHistoryOrders }
```

## Actual request

The actual request is made by using the [useQuery](https://www.apollographql.com/docs/react/data/queries/#executing-a-query) hook from Apollo Client (React).

---

Can you guys help me, please? Am I doing something wrong that I do not know about? Is this maybe a bug? 

Thanks!

**Comment by kettanaito** [comment]
Hey, @lenoirzamboni. Thanks for reporting this.

That `map` property is an internal property of the [`Headers` polyfill](https://github.com/mswjs/headers-utils/blob/14112f6bbb0dc7f24be92f2b4afb03a6c09066b8/src/Headers.ts#L4) that MSW uses in Node to operate with headers as with a [`Headers`](https://developer.mozilla.org/en-US/docs/Web/API/Headers) instance. That API is not supported by all request modules in Node, thus the polyfill. 

The issue is that the `map` property leaks to the request headers directly, which shouldn't happen. I wonder if it has to do with how `ctx.fetch()` works, not serializing the headers, for example.

**Comment by kettanaito** [comment]
I've noticed you are using an older version of `msw`: 0.22.0. Can you please update to the latest one?

**Comment by kettanaito** [comment]
Unfortunately, I cannot reproduce this issue with the latest library release. See the logic flow below.

First, `ctx.fetch()` accepts a mocked request instance (`req`) and derives proper `window.fetch` arguments out of it:

https://github.com/mswjs/msw/blob/b99be78eede52ebde08c48fc78f773cce3840a6c/src/context/fetch.ts#L49-L53

As a part of this transformation it executes the following logic in the `augmentRequestInit ` function:

https://github.com/mswjs/msw/blob/b99be78eede52ebde08c48fc78f773cce3840a6c/src/context/fetch.ts#L7-L15

You can see that `headers: headers.getAllHeaders()`. That's a public function of the aforementioned `Headers` class polyfill that returns the value of the internal `this.map` property:

https://github.com/mswjs/headers-utils/blob/14112f6bbb0dc7f24be92f2b4afb03a6c09066b8/src/Headers.ts#L53-L58

Thus, the `fetch` arguments are never given headers that contain the raw `Headers` value that'd include the `map` property. It always gets serialized into a plain object without any internal properties. My integration test also confirms that as the "production" server never receives malformed headers. 

The only difference between your use case and the test I've written is that you are running this logic in a browser. That difference shouldn't affect anything, as both browser and NodeJS use the same `ctx.fetch` code linked above. I'm also not using the `useQuery` hook, but the `apollo-fetch` library to make a request instead. That also shouldn't matter, because if there's an issue, it should be with how `ctx.fetch` transforms a mocked request into an actual one. Request issuing client matters not in this case.

**Comment by kettanaito** [comment]
@lenoirzamboni, you can see my test suite here: https://github.com/mswjs/msw/pull/550/files#diff-54d9f5a6274418c5a387bb6203137653c96ef4f8069e7101ad249a08abb9be8d. It's similar to your use case, just instead of an actual server I'm creating a test server that acts like one. That test server receives proper `req.headers`. 

Could you please take a look at my findings and the test and see if I've missed anything? Thanks.

**Comment by kettanaito** [comment]
Sorry, I wasn't able to reproduce this issue neither during manual testing nor automated integration test. If you still experience this, please create a reproduction repository that will help us debug and fix the problem.
