### ISSUE TITLE
Ability to capture/mock inbound requests in node (instead of outbound requests)

### ISSUE THREAD

**Issue by idolize** [mswjs/msw#548]
**Is your feature request related to a problem? Please describe.**
This is an entirely new feature for msw, but I think it would be awesome to be able to bootstrap a separate server process from my msw mock definitions.

Here's the scenario I'm hitting: I often use mocks (via msw in browser) when developing a new feature and it works great! However, I'm also adding Cypress e2e testing and I'd like to use those same mocks to run against my tests.

I've done some extensive researching into how to use msw with Cypress, but there are a couple of issues I've run into:
- Cypress `cy.request` bypasses any service workers. We use this to fetch some data in our e2e tests (rather than relying on the UI all of the time), but it does not return the mock data (as I would like) and instead bypasses msw.
- I tried to patch the Cypress node process itself to use `setupServer` from `msw/node`, but I had issues getting that to patch  Cypress properly (I think Cypress monkey patches the HTTP request function primitives themselves)
  - Even if I were to resolve this: I would run into issues due to the fact the memory context of the node process is separate from the one running in the service worker, so my changes would not be properly synchronized (my mock handlers write to an in-memory DB)

**Describe the solution you'd like**
After banging my head against the wall for a while I realized all this could be resolved if I just moved away from the in-browser service worker model and used a separate, single nodejs/express server process that can respond with my mock data (and update in-memory DB). However, this is not easily doable with msw (currently).

My suggestion is to add this feature as a separate target for msw. The logic should not be too different from the existing targets: parse the request handlers for the mocks and generate new express routes that can be attached to any express app (or as a "connect" middleware).

**Describe alternatives you've considered**
As previously mentioned, my goal is to be able to run Cypress with my same mocks as well as in the browser.

### I really like the convenience of using msw's service worker approach when just running the site locally (no need to spin up a separate server), but it has some limitations. Giving the developer the option to do both from the same set of mock definitions would be awesome!

**Additional context**
Cypress plugin attempt (did not work):

```js
on('task', {
  initMocks() {
    console.log('Initializing mocks');
    const server = setupServer(...handlers);
    server.listen();
    return null;
  },
});
```

I see this issue may be somewhat related, although it would still not solve the `cy.request` issue (as far as I can tell) https://github.com/mswjs/msw/issues/374

**Comment by idolize** [comment]
Managed to get a proof of concept working (which I can turn into a PR if desired):

```ts
import { Headers, flattenHeadersList, headersToList } from 'headers-utils';
import { MockedRequest, RequestHandler } from 'msw';
import { RequestHandlersList } from 'msw/lib/types/setupWorker/glossary';
import { Application, RequestHandler as Middleware } from 'express';

const delay = (ms: number) =>
  new Promise<void>((resolve) => {
    setTimeout(() => {
      resolve();
    }, ms);
  });

// Using getResponse from https://github.com/mswjs/msw/blob/2b133436cd405a9ebf6d6882d5b8e47997b943f6/src/utils/getResponse.ts
export const getResponse = async <R extends MockedRequest, H extends RequestHandlersList>(
  req: R,
  handlers: H,
): Promise<ResponsePayload> => {
  // Sadly this is not exported on the library so we have to copy/paste here
  // ...
};

function setupMswMiddleware(app: Application, handlers: RequestHandler[]) {
  const mswMiddleware: Middleware = async (req, res, next) => {
    const headers = new Headers();
    for (let i = 0; i < req.rawHeaders.length; i += 2) {
      headers.set(req.rawHeaders[i], req.rawHeaders[i + 1]);
    }
    const url = req.protocol + '://' + req.get('host') + req.originalUrl;
    const newReq: MockedRequest = {
      url: new URL(url),
      method: req.method.toUpperCase(),
      headers,
      cookies: req.cookies, // TODO use cookie-parser
      mode: 'same-origin',
      keepalive: false,
      cache: 'default',
      destination: '',
      integrity: '',
      credentials: 'include',
      redirect: 'manual',
      referrer: req.header('referer'),
      referrerPolicy: '',
      body: req.body as { query: string; variables: Record<string, any> },
      bodyUsed: !!req.body,
      params: req.params,
    };
    const { handler, response } = await getResponse(newReq, handlers);
    if (handler) {
      // MSW Matched Request
      res.status(response.status);
      flattenHeadersList(headersToList(response.headers as any)).forEach(([key, value]) => {
        res.setHeader(key, value);
      });
      if (response.delay) {
        await delay(response.delay);
      }
      res.send(response.body);
    } else {
      // No MSW match - move along
      next();
    }
  }
  app.use(mswMiddleware);
}

export default setupMswMiddleware;
```

Then you just use it via:

```ts
import express from 'express';
import setupMocksMiddleware from './mswMiddleware';

const app = express();
app.use(express.json());
if (useMocks) {
  setupMocksMiddleware(app, myHandlers);
}
// add other routes etc...
```

**Comment by kettanaito** [comment]
Hey, @idolize. Thank you for suggesting this and for the detailed motivation!

## Note on Cypress support

I admit that the current support for Cypress is rather limited. It's mainly related due to the way Cypress (and many other automation testing frameworks) runs, that being an iframe. That creates certain challenges in handling the registered worker's context.

We are, however, keeping this in mind and will try to provide the necessary improvements on our part so that MSW could be run in setups that function through iframes. See #374, #383. 

## Using `cy.request`

> Cypress `cy.request` bypasses any service workers. We use this to fetch some data in our e2e tests (rather than relying on the UI all of the time), but it does not return the mock data (as I would like) and instead bypasses msw.

Can you use native `fetch` instead of `cy.request`? 

The point of `cy.request` is for Cypress to provision a basic request interception layer and add an assertion functionality to it:

```js
cy.request('https://jsonplaceholder.cypress.io/comments')
  .should((response) => {
    expect(response.status).to.eq(200)
    expect(response.body).to.have.length(500)
    expect(response).to.have.property('headers')
    expect(response).to.have.property('duration')
  })
```

> Excerpt taken from the [Cypress documentation](https://example.cypress.io/commands/network-requests#request).

You _don't need to do this_ with MSW—it provisions request interception for you. In fact, you don't need to mock anything as a part of your test while using MSW. Combining both will not work as `cy.request` monkey patches `XMLHttpRequest` so it never does an actual request, so it doesn't hit the service worker. 

### Suggestion

First, reconsider the need to fetch resources as a part of your test rather than as a part of your app's runtime. This effectively means that the resources you fetch aren't fetched when your app executes. Perhaps there's no need to do that, as you're testing something that your application doesn't do for your customers.

If you absolutely must perform a request in a browser context as a part of a test,  use the native ways to perform a request and assert on the result. 

```js
test('example', async () => {
  // I'm not familiar with Cypress API to make a request in a browser.
  // This may differ. I highly suggest checking Cypress docs or community
  // resources for this. 
  const { fetch } = await cy.window().then(win => win.fetch)
  const res = await fetch('/resource')
  const json = await res.json()

  expect(json).toHaveProperty('firstName', 'John')
})
```

## Cypress plugin

> Cypress plugin attempt (did not work):

It didn't work because of `setupServer`. You don't want to intercept requests in the process that runs your tests (that's what your implementation did), but rather the requests that your application makes in the automated browser. Whenever there's a "browser" around, always use [`setupWorker`](https://mswjs.io/docs/api/setup-worker).

## Standalone server

I did have some thoughts about providing an API that would spawn an actual server based on your mock definitions. That, however, I wouldn't recommend in your case. 

## Recommended setup

The ideal Cypress + MSW setup is the following:

1. Cypress loads your application.
2. Your application creates and starts the worker via `setupWorker`. 
2. Your test asserts the app from the user's perspective: makes interactions, triggers requests. No stubbing involved.
3. Any request is resolved against your worker. This is exactly how MSW works for you during development. 
4. Application receives mocked responses. Cypress knows nothing about them. 

We have a [Cypress example](https://github.com/mswjs/examples/blob/0b39bc5863ff8c3052985e1cf159fe9d59707f8b/examples/rest-react/e2e/Login.e2e.test.js) featured in our examples repository. While it's rather bareboned, I believe it showcases the intention of how to combine the two libraries. However, we are open to improvement and understand that real use cases may require some additional support from the library. 

If you think the setup above is unsuitable, please tell us more about your use case. I'm specifically interested in what kind of requests do you make via `cy.request` that aren't performed as a part of your app?

**Comment by kettanaito** [comment]
While this is a good suggestion, we don't have this feature on our roadmap. I see little use in this issue being open as it's not going to be tackled any time soon. We'd most likely provide such functionality in a separate package, as it may be considered MSW's extension.

**Comment by idolize** [comment]
Hi @kettanaito - following up on this (I know it's been a while):

Your reply makes sense generally, but the Cypress docs [do encourage you to use `cy.request` as part of the test itself for things like seeding data or short-circuiting your UI layer](https://docs.cypress.io/guides/getting-started/testing-your-app#Bypassing-your-UI) and not just as a means of returning mock data to the UI.

What I'm looking to do is write one set of tests that I can point at either my mocks (currently written with msw) or my staging server (for true e2e testing).

I'm not really looking to mock specific requests in a hard-coded way for certain test cases (I may do that in some circumstances, but it's not relevant to this issue), which seems to be what is shown in the Cypress examples in the msw docs.

For my use case I still think having the ability to switch between a mock server and a real server would be helpful (including the use of `cy.request`), and it seems the best way to do that would be via a separate server process for the mocks.

**Comment by kettanaito** [comment]
That makes total sense, @idolize. I'm only here to point out that MSW is unlikely to co-exist well with any tools that function via request stubbing. We encourage the requests to actually happen, which is one of the main features of MSW, and also a technical requirement for such requests to be intercepted (stubbed requests don't hit the network and, thus, the worker). 

> I'm not really looking to mock specific requests in a hard-coded way for certain test cases (I may do that in some circumstances, but it's not relevant to this issue), which seems to be what is shown in the Cypress examples in the msw docs.

Treat it as a basic example, just as any other usage examples in the documentation/[examples repo](https://github.com/mswjs/examples) are. There are much more that developers achieve through MSW, including dynamic API scenarios, data-driven mocking, network outage tests, and so on. 

I encourage you to create a discussion in this repo, showing us your use case, so we could provide you with the best suggestions on how to approach it with MSW. 

> For my use case I still think having the ability to switch between a mock server and a real server would be helpful 

You can do that anytime by calling `worker.stop()` right from your test. Resume the interception by calling `worker.start()` again whenever your tests demand that.

**Comment by kettanaito** [comment]
Together with @idolize we've started the effort behind the [http-middleware](https://github.com/mswjs/http-middleware) extension to MSW that would allow to spawn an HTTP server given a list of request handlers, or apply the response resolving logic to an existing HTTP server using a middleware.
