### ISSUE TITLE
MSW error not visible to Axios

### ISSUE THREAD

**Issue by JCB-K** [mswjs/msw#573]
## Describe the bug
_(I'm not sure if this is an issue in axios or in MSW - feel free to redirect me if needed)_

When using fetch to do a request to a non-existing MSW resource it throws a helpful MSW error. However this error is not visible when using axios (which just throws a `Network error`), which can cause a lot of time debugging in the wrong direction.

## Environment

- `msw: 0.26.0`
- `nodejs: 12.20.1`
- `npm: 6.14.10` (but not used)

> Please also provide your browser version.

n/a

## To Reproduce
1. `git clone https://github.com/JCB-K/msw-axios-testcase`
2. `cd msw-axios-testcase`
3. `yarn`
4. `yarn test`

## Expected behavior
All tests should pass.

## Screenshots

![image](https://user-images.githubusercontent.com/636039/106429518-d8b53f80-646a-11eb-82b2-5934073d69c8.png)

## Axios or MSW?

Like I mentioned above, I'm unsure where the issue lies. Normally I would say axios since that is doing the request and MSW is just the server which should expose a network error. But this is a bit of a different kind of error since it happens in the same environment, and is probably caught in a different way?

**Comment by kettanaito** [comment]
Hey, @JCB-K. Thank you for reporting this and special thanks for putting down that amazing reproduction repository!

I can confirm the issue is there and it's related to how unhandled requests are treated by MSW given the "error" value to `onUnhandledRequest` option. In the current master the "error" value throws an exception:

https://github.com/mswjs/msw/blob/4a1e0acc67d4ee53fceb942a5284363f1c72d534/src/utils/request/onUnhandledRequest.ts#L34-L36

It looks like different request issuing clients handle that exception differently: 

- `fetch` propagates a thrown exception to the parental context. That's why you can catch it and assert its message.
- `axios` gracefully handles an exception during the request lifecycle as a network error. 

We are addressing how unhandled requests are treated as a part of #539. With that change, the "error" value will call `console.error` instead of throwing an exception. 

When I tested that PR in your repository I got both fetch and axios tests _failing_. That's because an unhandled request doesn't throw an exception, so it never halts the native fetch/axios execution. Instead, you get an `ENOTFOUND` error, because you're attempting to request a non-existing address. The unhandled request error message is also printed alongside your test:

```bash
console.error
  [MSW] Error: captured a OPTIONS http://api.mock/does-not-exist request without a corresponding request handler.

    If you wish to intercept this request, consider creating a request handler for it:

    rest.options('http://api.mock/does-not-exist', (req, res, ctx) => {
      return res(ctx.text('body'))
    })

Error: Error: getaddrinfo ENOTFOUND api.mock
  // stack trace...
```

Your use case gives us a great perspective over how converting the behavior from throwing an exception to `console.error` would affect the request issuing clients. I personally find an error message + a default client exception to be much more useful. 

@timdeschryver @marcosvega91 what do you think about this, gentlemen?

**Comment by JCB-K** [comment]
Nice! I think that https://github.com/mswjs/msw/issues/539 covers my use case. I don't necessarily need my client-side code to see the error MSW produces (I wouldn't see it if I requested a "real" server either), I just would want that that error to be visible when running tests since it would be a helpful nudge in the right direction.

> When I tested that PR in your repository I got both fetch and axios tests failing. That's because an unhandled request doesn't throw an exception, so it never halts the native fetch/axios execution. 

What node version are you running? It passes for me on both Node 12 and and Node 14.  EDIT: Sorry got it now - you tested the tests in my repo agains your PR. Yes I think it makes sense to have both: a failing request promise on the "client side" (which would also happen in real life), and a console.logged error on the "server" (MSW) side.

 Fetch managing to propagate the MSW error is actually the odd one here (not Axios), considering that the server and the client shouldn't be able to communicate outside regular request<->response.

**Comment by marcosvega91** [comment]
I think that logging the error should be a good choice here. Anyway, the behavior can be changed by updating the `onUnhandledRequest` option

**Comment by timdeschryver** [comment]
I have to agree with everything commented here 😁

**Comment by kettanaito** [comment]
I see this as yet another reason to tackle #539 as a `console.error` instead of an exception. For posterity:

- Exceptions in a request cycle are treated differently depending on a request client (fetch propagates, axios gracefully handlers).
- Forwarding a suggestion text to `stderr` results in a suggestion being printed while the original client request error thrown as well (given hitting a non-existing endpoint).
