### ISSUE TITLE
after dependency upgrade to 0.27, our TypeScript project cannot import { RestContext } from 'msw/lib/types/rest'

### ISSUE THREAD

**Issue by SchlauFuchs** [mswjs/msw#624]
## Describe the bug
Our typescript project is no longer able to import RestContext. Typescript compiulation fails with the message:
```TS2459: Module '"msw/lib/types/rest"' declares 'RestContext' locally, but it is not exported.```

## Environment

- `msw: 0.27.0`
- `nodejs: 14.15.4`
- `npm: 7.0.7`

## To Reproduce
1. create a typescript file. ours is called `handlers.ts`
2. add a line `import { RestContext } from 'msw/lib/types/rest';`
2. compile

## Expected behavior
No compile error.

**Comment by timdeschryver** [comment]
Have you tried importing it from `msw` directly? 
It seems like we export it our the [index file](https://github.com/mswjs/msw/blob/master/src/index.ts#L32), so it should be available there.

```
import { RestContext } from 'msw'
```

If that doesn't solve it, on what version was it working?

**Comment by kettanaito** [comment]
Version 0.27.0 introduced a breaking change to request handlers (see a full log of changes [in the release notes](https://github.com/mswjs/msw/releases/tag/v0.27.0)). Those changes included some types to be added, moved, or removed. I believe your issue is caused by importing a `RestContext` type that's no longer exported by the `rest.ts` module.

## How do I fix this?

Import the `RestContext` type from the `msw` package directly:

```ts
import { RestContext } from 'msw'
```

Generally, don't import things from the library's build as its structure may change _without being a breaking change_. Always import from the root package. Raise an issue if something is not exported from there.
