### ISSUE TITLE
msw fails to find the correct client in iframe scenarios (like with Cypress)

### ISSUE THREAD

**Issue by crunchy244** [mswjs/msw#643]
## Describe the bug
This is a tricky one. I suppose the root error is failing to find the correct client that emitted a specific event, which then throws an error in `./mockServiceWorker.js#117` on `if (activeClientIds.has(client.id))` because `client` is undefined.

It only happens in Cypress tests, which changes how the app is rendered I suppose, and has to do with iframes I guess.

More info in screenshots.

## Environment

- `msw: 0.27.1`
- `nodejs: 14.13.0`
- `npm: 7.6.1`
- `cypress: 6.6.0`
> msw@0.26.2 does not have this issue

Chrome: `89.0.4389.82`
> but also happens on Electron and Firefox, doesn't seem to be browser related

## To Reproduce
1. Run `msw` on app start
2. Run Cypress to test app (or another way to put app into an iframe?)
3. Re-run tests until error (usually first or second is enough)

> I realise this is bad, please take a look at the screenshots, perhaps it will become clearer how to reproduce

## Expected behavior
`msw` can be used in Cypress/iframes without issues.

## Screenshots

It starts by intercepting this request, I don't know why because it's definitely not a path I mock.
I suppose it should simply pass through.

![image](https://user-images.githubusercontent.com/18623773/110943984-c06ef500-8333-11eb-8818-326d1ddfd225.png)

It then finds the client, but it's `nested` so on to trying to find the parent I suppose?

![image](https://user-images.githubusercontent.com/18623773/110944202-0af07180-8334-11eb-8dec-44256a718435.png)

This is where it goes wrong. `allClients` has no id that matches one in `activeClientIds`.

![image](https://user-images.githubusercontent.com/18623773/110944415-59057500-8334-11eb-8367-ee2f1a781fee.png)

Therefore `client` is now `undefined` here, and `client.id` throws.

![image](https://user-images.githubusercontent.com/18623773/110944625-9964f300-8334-11eb-9a3e-bf311431292e.png)

I hope that helps, I'm sure it has to do with iframes but I don't know why the ids don't match.

Curiously, the first Cypress test always passes (ids match and all), but the second on always fail.

**Comment by tget4** [comment]
I'm having the exact same problem. The client id for the incoming event doesn't match any of the active clients. I'm running a nextjs server and it blows up on any request to `/__cypress/` or `/_next/`.

Updating line 117 on mockServiceWorker.js to this seems to resolve the problem 

```
  if (client && activeClientIds.has(client.id)) {
 ```

**Comment by Wimpert** [comment]
> I'm having the exact same problem. The client id for the incoming event doesn't match any of the active clients. I'm running a nextjs server and it blows up on any request to `/__cypress/` or `/_next/`.
> 
> Updating line 117 on mockServiceWorker.js to this seems to resolve the problem
> 
> ```
>   if (client && activeClientIds.has(client.id)) {
> ```

I encountered the same issue (using storybook, msw and cypress). And indeed, I was able to fix it by doing exactly the solution provided above.

**Comment by kettanaito** [comment]
Thanks for reporting this.

> It starts by intercepting this request, I don't know why because it's definitely not a path I mock.

That's expected, the worker intercepts _all_ requests. That's how it can distinguish which to mock and which to bypass.

> This is where it goes wrong. `allClients` has no id that matches one in `activeClientIds`.

I wonder does that mean that the previously existing client (`5441c...`) got removed due to some iframe change? The logic accounts that if a client A registered the worker (stored in `activeClientIds`) is always present. Looks like your use-case proves this assumption wrong. 

@tget4, thank you for the pull request!

**Comment by kettanaito** [comment]
The fix looks good, but we need to get a test so this doesn't happen again. I'm trying to emulate an iframe reload scenario in Playwright, and it doesn't seem to be working as we need. 

Please, can anybody share some context _when_ exactly this happens? (test suite change, page reload, navigation, etc.) Any details will be helpful to finding the root cause and writing a test for that. Thanks.

**Comment by Wimpert** [comment]
> The fix looks good, but we need to get a test so this doesn't happen again. I'm trying to emulate an iframe reload scenario in Playwright, and it doesn't seem to be working as we need.
> 
> Please, can anybody share some context _when_ exactly this happens? (test suite change, page reload, navigation, etc.) Any details will be helpful to finding the root cause and writing a test for that. Thanks.

In my case it happens when I hit the rerun button in Cypress.

**Comment by kettanaito** [comment]
Thank you, @Wimpert! Now to figure out what the "rerun" button actually does...

**Comment by tget4** [comment]
For me it was happening if I change code, refreshed the page, or clicked the rerun button. I'll see if I can reproduce in playwright.

**Comment by kettanaito** [comment]
There's a challenge with refreshes in Playwright: a refresh destroys the previous execution context (sort of expected). I've tried reloading the frame itself, but it simply fails the test with the execution context exception. I might have done something wrong.

**Comment by nselikoff** [comment]
This has surfaced in the cypress repo as well: https://github.com/cypress-io/cypress/issues/15434

In my case it happens when I hit the rerun button in Cypress' UI, but also with test suite and code changes that recompile the app and trigger cypress to re-run the test. The proposed fix (https://github.com/mswjs/msw/issues/643#issuecomment-797505097) seems to resolve the issue for me as well.

More details on my setup: https://github.com/cypress-io/cypress/issues/15434#issuecomment-807275725

**Comment by bitttttten** [comment]
I am hitting this too, but I found it very hard to pinpoint exactly what is happening since I only had the issue when running headless tests in cypress, and so I didn't have access to any debugger tools 🙃 

For now I applied the patch in the cypress thread (`if (client && activeClientIds.has(client.id)) {`) and it's working. Although yeah sadly I can't give much more info apart from what I posted in cypress-io/cypress#15434 since it's hard to see what's going on.
