### ISSUE TITLE
getting an unhandled request error for requests that are handled but intended to be forwarded on

### ISSUE THREAD

**Issue by kentcdodds** [mswjs/msw#655]
## Describe the bug

When using `server.listen({onUnhandledRequest: 'error'})`, I expect to see errors when there's an unhandled request, but not when the request is handled with a `return undefined`.

## Environment

- `msw: 0.27.1`
- `nodejs: 14`
- `npm: 6`

> Please also provide your browser version.

## To Reproduce

1. Clone https://github.com/kentcdodds/msw-handler-error-bug
2. Install
3. Run `node index.js`
4. See error when `mock = false` but no error when `mock = true`

## Expected behavior

There should be no error

## Screenshots

![image](https://user-images.githubusercontent.com/1500684/111660552-d10be900-87d3-11eb-9ad1-c4e5cbaf87eb.png)

**Comment by marcosvega91** [comment]
hellooo,

this is true. This is implemented in this way because you can have a generic handler like 
```js
rest.get('*', (req) => {
  console.log(req.body)
})
```
that is only used for debugging. The handler above is not specific for your request so for us is an unhandled request. 
This is happening also for your case where you want to return nothing if a condition is satisfied. 

I think that we can not throw an error if there is at least one handler for the request even with no response. What you think @kettanaito ?

**Comment by kentcdodds** [comment]
What is instead of returning undefined, we return something that indicates intent (like: please make the actual request)

**Comment by marcosvega91** [comment]
an idea could be to add a new method to `response` object like

```js
const server = setupServer(
  rest.get('https://randomuser.me/api', (req, res, ctx) => {
    if (!mock) return res.forward()
    return res(ctx.json({mocked: true}))
  }),
)
```

**Comment by kentcdodds** [comment]
Yep, I like that

**Comment by kettanaito** [comment]
> that is only used for debugging

That is not entirely true. You can do multiple things in a request handler, mocking a response being one of them. You can also monitor requests without affecting their responses. Currently, that's done implicitly whenever your handler:

- Doesn't return anything.
- Explicitly returning nothing.

We may not be giving this behavior enough light so it appears as magic to the users. We mention it in the [Response resolver fundamentals](https://mswjs.io/docs/basics/response-resolver#conditional-response). That'd be a documentation task. 

The issue that Kent experiences is caused by the bug in our logic that decides to call the `onUnhandledRequest` callback. The intent is to call that callback when there is _no handler for a request_. In his case, there is a handler, it just doesn't return anything. That scenario must not produce the unhandled request warning/error. 

> I think that we can not throw an error if there is at least one handler for the request even with no response

We should call the `onUnhandledRequest` when:

- There are no matching handlers.
- There is a matching handler that returned no mocked response. 

Both these scenarios mean the request was performed as-is, making it unhandled. This needs to be converted into an integration test describing the intended behavior, as this issue is clearly a regression that went unnoticed after Request Handler API refactoring.

> an idea could be to add a new method to `response` object like

I like the wording, but we need to be careful about such an API. I wouldn't force the users to always return something from a handler. This means that the lack of return, `return null`/`return undefined` and `return res.forward()` do the exact thing in a different way. I would rather have a single way to bypass the mocking, that being the lack of returned mocked response. 

Semantically, the `res()` function and the object it composes represent a _mocked response_. I don't think it's a good idea to add a method related to an actual response. In other words, `res()` doesn't decide whether to mock or not, the handler does. This allows us to keep `res()` predictable. Based on the established boundaries, such forwarding utility could reside on the `ctx`:

```js
rest.get('/api', (req, res, ctx) => {
  if (!mocked) {
    return ctx.forward()
  }
})
```

Context is much less strict as to what it does, as it may act as composition parts for the mocked response, or dispatch original requests via `ctx.fetch()`. This needs to be discussed as a standalone feature.

**Comment by kettanaito** [comment]
There's a single consideration: when you have a matching handler, but forgot to return a mocked response, you won't see any warning about that. Currently, when you do this with in-browser API, you receive a warning:

https://github.com/mswjs/msw/blob/fb2dd333f8ff731f76ec123ebdb47b7318f7245a/src/utils/worker/createRequestListener.ts#L62-L68

There's no such logic in Node.js:

https://github.com/mswjs/msw/blob/fb2dd333f8ff731f76ec123ebdb47b7318f7245a/src/node/createSetupServer.ts#L108-L117

In Node.js, this would mean that in your case it would print a warning, assuming you might have forgotten to return a mocked response from the handler. I don't think that's the behavior you expect. Disabling logs entirely to suppress a single warning isn't a good way to go either. 

It's a tough balance between providing useful suggestions and not cluttering the stdout. As there is no way to differentiate if you have an explicit return, implicit return, or unintentionally forgot to return a mocked response, I lean towards no warnings being the safest option. It may look unintuitive to debug the scenarios when you forget things, but we can approach that with something like a `debug: true` option on the worker/server. In other words, don't assume the user made a mistake by default.

**Comment by kentcdodds** [comment]
> when you have a matching handler, but forgot to return a mocked response, you won't see any warning about that.

This wouldn't be the case with `ctx.forward()` though right? That's the API I'd prefer anyway.

**Comment by kettanaito** [comment]
Yes, with an explicit API to forward the request it wouldn't be an issue anymore. A request could be considered unhandled based on the sole criteria if there was a mocked response returned, or the request was forwarded. Returns won't play any role in that logic anymore. 

We should consider `ctx.forward`, which may be a nice feature to discuss.

**Comment by kentcdodds** [comment]
Well, I'm all for it! I say let's go forward with `ctx.forward` 😆

**Comment by kettanaito** [comment]
Hey, @kentcdodds 👋 I've merged `req.passthrough` in #1204 but we cannot release it just yet. We need to figure out the issue behind #1175. Please, if you have any insight about that TypeScript behavior (or know somebody who may have), I'd be thankful!

**Comment by kentcdodds** [comment]
Ah, dang. I think this is above my level of experience 😬
