### ISSUE TITLE
Storybook not working for lit-element

### ISSUE THREAD

**Issue by zaidchauhan** [mswjs/msw#670]
## Describe the bug
I am trying to use mswjs for web component built with lit-element. 
I already followed the example mentioned here - https://github.com/mswjs/examples/tree/master/examples/with-storybook 

Mocking for the development and unit tests works fine. However, for storybook, it does not work. I am seeing a message that Mocking is enabled in console.

Here is my example repo - https://github.com/zaidchauhan/lit-with-mswjs 

## Environment

- `msw: 0.28.0`
- `nodejs: 12.17.0`
- `npm: 6.14.8`

> Please also provide your browser version.
Chrome:  89.0.4389.90

## To Reproduce
1. Clone repo https://github.com/zaidchauhan/lit-with-mswjs
2. npm install
3. npm run storybook

## Expected behavior
It should work

## Screenshots
![image](https://user-images.githubusercontent.com/7615481/113114695-e50c0d80-920b-11eb-86be-36d5dabb5b2b.png)

**Comment by zaidchauhan** [comment]
@kettanaito Any comments?

**Comment by kettanaito** [comment]
Hey, @zaidchauhan. 

I've linked a related issue in the `msw-storybook-addon` (which you should be using for MSW + Storybook integration). It seems like a bundler issue but it may require more investigation to be precise. 

- See https://github.com/mswjs/msw-storybook-addon/issues/50

I'm closing this issue because it's not something we can/should be tackling at the MSW side. Thank you for understanding.
