### ISSUE TITLE
[Error] Headers x-msw-request-id forbidden at dispatchError / Buffer.js

### ISSUE THREAD

**Issue by grap3fruit** [mswjs/msw#716]
## Environment

| Name | Version |
| ---- | ------- |
| msw  | 0.28.2   |
| node | 12.18.0  |
| OS   | Mac OS Catalina 10.15.5  |

## Request handlers

```js

import { setupServer } from 'msw/node'
import { rest } from 'msw'

const handlers = [
  rest.get(SOME_API, (req, res, ctx) => {
      return res(ctx.json(''));
    },
  ),
];

const server = setupServer(...handlers);

beforeAll(() => server.listen());
afterEach(() => server.resetHandlers());
afterAll(() => server.close());

test('some test..', async () => {
  server.use(
    rest.get('/api/1/..', (req, res, ctx) => {
      return res(ctx.json({...}));
    }),

    rest.get('/api/2/..', (req, res, ctx) => {
      return res(ctx.json({...}));
    }),
  );

  render(<Component />);
  await waitFor(() => screen.getByText(/test test/i));

});

test('some test2..', async () => {
  server.use(
    rest.get('/api/1/..', (req, res, ctx) => {
      return res(ctx.json({...}));
    }),

    rest.get('/api/2/..', (req, res, ctx) => {
      return res(ctx.json({...}));
    }),
  );

  render(<Component />);
  await waitFor(() => screen.getByText(/test test2/i));

});

...

test('some test8..', async () => {
  server.use(
    rest.get('/api/1/..', (req, res, ctx) => {
      return res(ctx.json({...}));
    }),

    rest.get('/api/2/..', (req, res, ctx) => {
      return res(ctx.json({...}));
    }),
  );

  render(<Component />);
  await waitFor(() => screen.getByText(/test test8/i));

});


```

## Actual request

I think it is not important.

## Current behavior

```
Error: Headers x-msw-request-id forbidden
        at dispatchError (/Users/.../node_modules/jsdom/lib/jsdom/living/xhr/xhr-utils.js:62:19)
        at validCORSPreflightHeaders (/Users/.../node_modules/jsdom/lib/jsdom/living/xhr/xhr-utils.js:99:5)
        at Request.<anonymous> (/Users/.../node_modules/jsdom/lib/jsdom/living/xhr/xhr-utils.js:372:12)
        at Request.emit (events.js:315:20)
        at Request.onRequestResponse (/Users/.../node_modules/request/request.js:1059:10)
        at ClientRequestOverride.emit (events.js:315:20)
        at ClientRequest.<anonymous> (/Users/.../node_modules/@mswjs/interceptors/src/interceptors/ClientRequest/createClientRequestOverride.ts:324:14)
        at ClientRequest.emit (events.js:327:22)
        at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:596:27)
        at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17) undefined

```
```
buffer.js:210
throw new ERR_INVALID_ARG_TYPE('target', ['Buffer', 'Uint8Array'], target);
^

TypeError [ERR_INVALID_ARG_TYPE]: The "target" argument must be an instance of Buffer or Uint8Array. Received null
at _copy (buffer.js:210:11)
at Buffer.copy (buffer.js:768:12)
at Request.<anonymous> (/Users/.../node_modules/jsdom/lib/jsdom/living/xhr/XMLHttpRequest-impl.js:864:11)
at Request.emit (events.js:315:20)
at Gunzip.<anonymous> (/Users/.../node_modules/request/request.js:1073:12)
at Gunzip.emit (events.js:315:20)
at addChunk (_stream_readable.js:295:12)
at readableAddChunk (_stream_readable.js:271:9)
at Gunzip.Readable.push (_stream_readable.js:212:10)
at Gunzip.Transform.push (_stream_transform.js:152:32) {
code: 'ERR_INVALID_ARG_TYPE'
}
```

## Expected behavior

**Just All PASS!!**

## Comment

I wrote many test code. but only when i use many msw api in one test file, this error was happen.
(Actually it is hard to say many because it happen with 4~8 test function in one file)

when i used 0.21.2 version, I only got error 'buffer.js:210'.
After update 0.28.2 version, I got additional error 'Headers x-msw-request-id forbidden'.

The bigger problem is sometimes the test passes, even though most time it fails.  
The only one solution what i found is, divide each test function in a different test file, like component1.test.tsx, component2.test.tsx, ... component6.test.tsx.  
Then the result is all passed.  

I guess the cause is maybe promise or memory leak problem.

Could i get some help? 🙏

**Comment by kettanaito** [comment]
Hey, @grap3fruit.

I'm afraid I must ask you for more details, especially about the actual data you provide to `ctx.json` and _how you make an actual request_. No need to share sensitive data, so feel free to substitute it with a compatible one. 

> Error: Headers x-msw-request-id forbidden

This error most likely means that your handlers don't catch the request you're making. I suspect that request handlers URL are not correct (this is the most common reason). Please enable the `onUnhandledRequest` option in your `server.listen()` call:

```js
beforeAll(() => server.listen({ onUnhandledRequest: 'error' }));
```

> throw new ERR_INVALID_ARG_TYPE('target', ['Buffer', 'Uint8Array'], target);

This error is interesting, primarily because I don't see any MSW-related modules in its stack trace. There's a chance you're not constructing a proper request/response body, and `jsdom/lib/jsdom/living/xhr/XMLHttpRequest-impl.js` fails to handle it as a Buffer. This may also be some of the MSW dependencies not handling the payload properly, that's why I asked for more information above. 

If you have a chance, please create a reproduction repository with this issue and share it here. If not, we'll have to gather the info by bits and pieces until we arrive to the solution.

**Comment by kettanaito** [comment]
If we dive into the `jsdom/lib/jsdom/living/xhr/XMLHttpRequest-impl.js` call, we'll see this:

```js
chunk.copy(properties.responseBuffer, properties.totalReceivedChunkSize - chunk.length, 0, chunk.length);
```

It throws on the attempt to copy the response buffer (`chunk.copy`). The `properties.responseBuffer` isn't a valid Buffer. This once more implies that there's an issue with how a response is constructed, and it may as well be an issue in your side until you show us the actual responses.

**Comment by grap3fruit** [comment]
Thanks for your detailed guidance. I will try to create reproduction repository. But it takes a time. 

And I used { onUnhandledRequest: 'error' }. It shows some error log. I think it happen cause of msw, not itself. 

The error logs were showed in exception handler area.
```
[MSW] Warning: captured a request without a matching request handler:
    
      • POST https:://some_exception_handler_url_api/
    
    If you still wish to intercept this unhandled request, please create a request handler for it.
    Read more: https://mswjs.io/docs/getting-started/mocks
```
I think some msw errors lead code to exception handler area.
The reason is, when i divide test function in different test file(not change logic at all), it all passed without any error, warning..! 

Anyway, I guess maybe there is a problem at the response of promise. Something makes missing out the response.

**Comment by marcosvega91** [comment]
I have opened also a discussion about this issue #713

**Comment by kettanaito** [comment]
The warning you've posted above means that your request isn't intercepted by MSW. This is likely due to different request URLs in your handler and in the actual request. **Please compare those carefully**. Once again, you've stripped the actual/expected URLs from the info, so there isn't much I can help with.

Since your request gets performed as-is (to the actual endpoint), that endpoint is likely to error on the presence of the `x-msw-request-id` header. That's not exactly an issue, as your setup doesn't satisfy the intention. 

Yeah, a reproduction repository would be best. It's okay if it takes time. It saves much more for the maintainers to get to the root cause and fix it. Thanks for understanding that.

**Comment by kettanaito** [comment]
Check your request URL, it looks like your actual request URL has an invalid protocol (`http:://` instead of `http://`):

```
• POST https:://some_exception_handler_url_api/
```

I'm closing this, as there hasn't been any reproduction scenario provided. My reply above still stands: most likely the request handler you wrote cannot capture the request you make (very likely a URL mismatch). Feel free to post the link to the reproduction repository so we could take this further. Thanks.
