### ISSUE TITLE
Making custom handlers requires a defineContext function

### ISSUE THREAD

**Issue by kentcdodds** [mswjs/msw#72]
The docs don't mention anything about this and I'm not sure of an ergonomic way to create this function...

**Comment by kettanaito** [comment]
That's a good point, @kentcdodds. Could you please show me how are you creating a custom request handler and what is your goal?

The `defineContext` function is used internally to define which `ctx` utility functions are available for specific request handlers. There are two main groups of request handlers, per docs: `rest` and `graphql`. Since those operate in different domains, they have different context utilities declared by `defineContext`, which establishes them in the third argument of a response resolver: `ctx`.

However, as of [Custom context utilities](https://redd.gitbook.io/msw/recipes/custom-context-utility) I see little benefit in passing them to `defineContext`, as you may import your custom context functions manually. I think it's a matter of marking `defineContext` as optional when creating a custom request handler, and describing what this function does for general knowledge in the documentation.

**Comment by kettanaito** [comment]
As of `0.9.2` the `defineContext` property is no longer required on a custom request handler.

I've updated the [Custom request handler](https://redd.gitbook.io/msw/recipes/custom-request-handler) documentation to reflect on how to use the `defineContext` property to provide your custom context utilities. 

I still don't recommend `defineContext` as the go-to, and would advise to just declare custom context utility functions and import them manually, but I can still see a use case of creating your own custom set of request handlers and even putting them into a separate package to distribute in the stack.

**Comment by kentcdodds** [comment]
Thank you!
