### ISSUE TITLE
REST query is mistaken for GraphQL query and can't be intercepted (throws an error)

### ISSUE THREAD

**Issue by thomasmery** [mswjs/msw#732]
## Environment

| Name    | Version |
| ------- | ------- |
| msw     | 0.28.2   |
| browser | Chrome     |
| OS      | Mac OS X Catalina    |

## Request handlers

no request handler for the following rest request 

```js
https://api.dev/artists?query=Petit+Biscuit&page=0&limit=5&workspaceId=ce54f030-2191-40b1-8b2a-cd5167e9ec5f
```

## Actual request

```js
const results = await Axios.get('/artists', {
    params: {
      query,
      page,
      limit,
      workspaceId,
      onlyBelieveArtists,
    },
  });
```

## Current behavior

Browser console throws an error : 

> [MSW] Failed to intercept a GraphQL request to "GET https://api.dev/artists": cannot parse query. See the error message from the parser below.

## Expected behavior

no error shoud be thrown as it is not a GraphQL request

this happens in 

`parseGraphQLRequest` method

seemingly because it relies on the presence of a _query_ param to start and parse the query

should this method even be called? maybe it should as no rest handler is provided it also tries to find a graphQL handler

thanks for any input on this

**Comment by kettanaito** [comment]
Hey, @thomasmery.

Do you have any request handlers defined at all? If so, could you please post them?

Looks like the issue happens when MSW attempts to call `onUnhandledRequest` for this request for which you have no request handler defined:

https://github.com/mswjs/msw/blob/9caef0a082e8c0f6f3d013f35c1626b3b08cbabb/src/utils/request/onUnhandledRequest.ts#L129

In order to provide meaningful handler suggestions, it first needs to parse the request as REST/GraphQL. I believe in the case of running under `onUnhandledRequest`, it shouldn't throw an exception on invalid `query`, because the request type is ambiguous at this point (whereas when run in a GraphQL handler we know you're expecting GraphQL, so throwing on an invalid query is a viable behavior).

We could benefit from wrapping the `parseGraphQLRequest` call in a function that'd silence any exceptions raised, because they are not relevant in the current execution context:

```js
const parsedGraphQLQuery = tryCatch(() => parseGraphQLRequest(request))
```

And the utility would be:

```ts
export function tryCatch<Payload>(fn: () => Payload): Payload | null {
  try {
    const payload = fn()
    return payload
  } catch (error) {
    return null
  }
}
```

Please, would you be interested in opening a pull request with this fix? We could use your help.

**Comment by thomasmery** [comment]
Hi @kettanaito 

thanks for the quick reply

I actually made a mistake when reporting but the error is not thrown but only printed to the console

https://github.com/mswjs/msw/blob/9caef0a082e8c0f6f3d013f35c1626b3b08cbabb/src/utils/internal/parseGraphQLRequest.ts#L143 

makes this check

```js 
 if (!input || !input.query) {
    return undefined
  }
```

that allows the parsing to occur when _query param_ is present

if it can't parse it just says so and I believe the rest of the handler selection can happen

I'd be happy to help but I confess I don't know why 

https://github.com/mswjs/msw/blob/9caef0a082e8c0f6f3d013f35c1626b3b08cbabb/src/utils/request/onUnhandledRequest.ts#L129

is made before the rest of the handler selection, at this stage I don't know if it is possible to tell that a request is definitely not a graphQL request and should not be parsed

the error printing is just confusing when you're not using GraphQL, even if it does not seem to cause a pb

FYI my handlers resemble this one

```js
const handlers = [
  rest.get(`${apiBaseUrl}/products/capi/album/:albumId`, (req, res, ctx) => {
    const mockedResponse = fixtures.products;
    return res(ctx.status(200), ctx.json(mockedResponse));
  }),
];
```

**Comment by kettanaito** [comment]
Your request has no matching request handler, so MSW attempts to handle it via `onUnhandledRequest`. That's only to produce a warning/error if you set it up to do so. It also attempts to parse _all_ unhandled requests to provide you with smart suggestions based on your existing handlers (maybe you made a typo). It's during that step that it fails because it assumes it can safely call `parseGraphQLRequest` on an arbitrary request, which isn't the case.

That's why I'm suggesting to wrap the `parseGraphQLRequest` call _only in the onUnhandledRequest_ function to ignore any thrown exceptions/errors. If the parsing uses `console.error` to print out the parsing error, I'd argue it should throw instead. That way its exceptions can be handled in the parental scope.

**Comment by thomasmery** [comment]
thanks,

makes sense if I turn the _logging_ into a _throwing_

I'll try and open a PR by the end of the week :)

**Comment by kettanaito** [comment]
We can try to

1. Throw an exception instead of logging an error.
2. Wrap the `parseGraphQLRequest` call in the `onUnhandledRequest` function in something like `maybe` or `tryCatch` custom function that would silence any exceptions thrown. 

Thank you for your support!
