### ISSUE TITLE
Make console.warn configurable for resolvers that do not return a mocked response.

### ISSUE THREAD

**Issue by chiller-whale** [mswjs/msw#771]
I am using `supertest` to test an API that integrates with a 3rd party http service. I have unhandled requests configured to error, but noticed that an error was being caused by a requests being sent with supertest. I was able to resolve this by using conditional mocking with: 
``` javascript
rest.get('http://127.0.0.1:*', () => {
  return;  
})
```

This solved the issue of erroring, but I now get a console.warn for each of those tests reading:
`[MSW] Expected a mocking resolver function to return a mocked response Object, but got: undefined. Original response is going to be used instead.`

It would be great if this warn could be disabled. If not globally, then through the `res` parameter so it could be handled on a per handler basis.

**Comment by chiller-whale** [comment]
After digging through the source, it looks like the header `x-msw-bypass` could be used as a work around.

**Comment by kettanaito** [comment]
Hey, @chiller-whale. Could you please include your mocks (request handlers, how you call `setupServer`) and your test that uses `supertest`, which surfaces an issue?

Returning undefined is a correct strategy for response resolvers since [0.28.1](https://github.com/mswjs/msw/releases/tag/v0.28.1). Please, could you check that you're running the latest version of `msw`?

```sh
$ npm install msw@latest
# or
$ yarn add msw@latest
```
