### ISSUE TITLE
Issue removing `content-type` header in mocked response

### ISSUE THREAD

**Issue by pkkummermo** [mswjs/msw#776]
## Environment

| Name | Version |
| ---- | ------- |
| msw  | 0.29.0   |
| node | 15.14.0 |
| OS   | WSL Ubuntu 18.04     |

## Request handlers

```js
      server.use(
        rest.get(TEST_URL, (_, res) => {
          return res((res) => {
            res.status = 200;
            res.headers.delete("content-type");
            res.body = "success with no content-type";

            console.log(res) // <---- res with no content-type in header

            return res;
          });
        }),
      );
```

## Actual request

```js
import "whatwg-fetch"; // <--- Using polyfilled fetch

fetch(TEST_URL)
.then((response) => {
        console.log(response.headers.get("content-type")); // logs "text/plain"
});
```

## Current behavior

I'm testing an edge case where a library should handle not having a `content-type` header present (there's a reason behind this, but you know TLDR), and I'm seeing that the mocked request is returned with an `content-type`, even though it logs no such thing in the `res` return function after being deleted by using `res.headers.delete("content-type");`

## Expected behavior

I want the response to omit the `content-type` header as it was deleted on the mocked response object.

TBH I don't know if this is some "sane defaults" that kicks in on msw or fetch (could not find anything after some googling), but if some of you could shed some light in whether msw tries to "guess" the content-type if the field is omitted that would put my heart at ease :) 

Thanks again for a great lib <3

**Comment by kettanaito** [comment]
Hey, @pkkummermo. Thank you for the kind words. 

This is an implicit behavior of `whatwg-fetch`: it will enforce a `Content-Type` header on a response body, if it doesn't have one:

https://github.com/github/fetch/blob/7727e50493eafae9a7005f10f18f81e5bbcbfdd3/fetch.js#L250-L258

Since you're responding with a text response body, it'll set the `text/plain` content-type header:

```js
res.body = "success with no content-type"
```

Unfortunately, there isn't much we should do on the MSW side. If this implicit behavior prevents you from testing your logic properly, consider setting a `Content-Type` to an empty string, or using a different fetch polyfill.

**Comment by pkkummermo** [comment]
Thank you for the quick answer :)

**Comment by pkkummermo** [comment]
For others having the same issue, [node-fetch](https://github.com/node-fetch/node-fetch) doesn't do any assumptions on the content-type and "fails" the right way :) 

so instead of 
```ts
import "whatwg-fetch";
```
you replace it with
```ts
const fetch = require("node-fetch");

if (!globalThis.fetch) {
  globalThis.fetch = fetch;
}
```
