### ISSUE TITLE
"Cannot read property 'id' of undefined" in Storybook (HMR)

### ISSUE THREAD

**Issue by Zombobot1** [mswjs/msw#788]
## Describe the bug
MSW intercepts storybook  HMR requests and fails them. As the result storybook cannot load anything and worker has to be stopped using dev tools.

## Environment

- `msw: 0.27.2`
- `nodejs: 16.0.0`
- `npm: 7.14.0`
- @storybook/react: 6.2.9

> Chrome:  91.0.4472.77

## To Reproduce

Story code
```ts
import React, { useEffect } from 'react';
import { Meta } from '@storybook/react';
import { rest, setupWorker } from 'msw';

(async () => {
  const worker = setupWorker(
    rest.get('http://localhost:5000/ping', (req, res, ctx) => {
      return res(ctx.json(['pong']));
    }),
  );
  await worker.start();
})();

const T = () => {
  useEffect(() => {
    fetch('http://localhost:5000/ping').catch(console.log);
  }, []);
  return <div>Div</div>;
};

export default {
  title: 'MSW/MSW',
  component: T,
} as Meta;

export const Example = T.bind({});
````

1. Go to story
2. Click on Toggle device tool bar in chrome devtools (to see mobile version of the site)
3. See bunch of error in console

## Expected behavior
Storybook loads the page

## Screenshots
Error example
![image](https://user-images.githubusercontent.com/48030070/122654652-2f3ac600-d14d-11eb-8af0-e7b7af23a70d.png)

**Comment by webpro** [comment]
See https://github.com/mswjs/msw/issues/785#issuecomment-864542454

tl/dr; bug probably introduced in v0.25.0, downgrade to v0.24.4 may be a temporary work-around.

@Zombobot1 could you please confirm this?

**Comment by Zombobot1** [comment]
@webpro thank you, after downgrading the error is gone

**Comment by ronkorving** [comment]
Is this the problem of ending up in a reload-loop?
That's what I'm experiencing in my Vue app.

Turning off live reload and HMR (ie: there's still a connection to the webpack dev server, but it's not reloading my browser on file change anymore).

If I change the [`location.reload()`](https://github.com/mswjs/msw/blob/1562bfc901c930bffc8c5eb150bb855b54020676/src/setupWorker/start/utils/getWorkerInstance.ts#L25-L32) line of code in `msw` to a `console.log`, I see it printed. And when I print, as may be expected because of the if-statement surrounding `location.reload()`, the value of `navigator.serviceWorker.controller` is `null` (`mockRegistrations` has one entry).

Is there anything I can do to help debug as to why `navigator.serviceWorker.controller` is `null`? I'm new to ServiceWorkers (this is my very first time depending on something that uses them).

Also: is the same issue as others in this thread are experiencing or a whole different issue altogether?

**Comment by kettanaito** [comment]
Hey, @ronkorving. Most likely the issue you're experiencing is the same issue reported here. MSW does a page reload intentionally if the `navigator.serviceWorker.controller` is `null` in a successful worker registration scenario. This is implemented for the following reasons:

https://github.com/mswjs/msw/blob/1da34e4fef13e278043d65ad656875186ac84e90/src/setupWorker/start/utils/getWorkerInstance.ts#L25-L33

What I'd suggest checking is the `mockRegistrations` array. We need to ensure that the library's worker has indeed successfully registered and there are no false-positive entries in that array. If everything is okay there, then the issue is that the `navigator.serviceWorker.controller` becomes `null`. 

There have been reports about a similar issue in Cypress (#744) and NextJS (#765), and I think they all may have a single root cause, that being some change in how HMR/Fast Refresh started to work. This still doesn't mean that we cannot tackle it on the library's side, we just need to decide if that'd be a proper solution.

> As a side note, it would be nice to limit the number of reloads MSW provisions, so that an application doesn't get stuck in an infinite reloading loop. After reaching the maximum number of retries, MSW may print an error message and stop reloading after that.

**Comment by ronkorving** [comment]
@kettanaito 
Thanks for your response. Given that you suggest this is likely the same kind of problem, I will keep responding in this issue.

I've logged the `mockRegistrations` array, and would like to share this screenshot from my browser console, if it helps:

<img width="583" alt="image" src="https://user-images.githubusercontent.com/631240/124233258-9ee98180-db4d-11eb-972f-86ab011a18c5.png">

You're looking at the output of:

```js
console.log('location.reload();', navigator.serviceWorker.controller, mockRegistrations);
```

Which I put in where the `location.reload()` normally happens.

This is in Chromium, and I had to click and a bunch of `...` properties to get their values displayed, I'm guessing because of all the getters. I think that implies that those values are not the values at the time of logging, but rather at the time of clicking `...`. But in the hope that that doesn't matter, I'm sharing this. Maybe it provides some insight.

If you would like me to dig into any properties in specific, let me know and I will dig.

Here's a screenshot of my "ServiceWorkers" panel of the "Application" tab in Chromium Dev Tools:

<img width="949" alt="image" src="https://user-images.githubusercontent.com/631240/124410013-7c8d7900-dd84-11eb-9aa3-0e26dc933f3a.png">

**Comment by ronkorving** [comment]
**Resolved**

I've finally been able to resolve this. I tried many things before, but I'm guessing some combination of changes has made it work. I can't fully retrace my steps, but will document what I can:

What I know I changed only recently is the `scope` option.

My setup is as follows:

- I serve up my root file (ie: my "index.html") on `http://localhost:8080/`, so really at the root.
- `mockServiceWorker.js` is being served from `http://localhost:8080/mockServiceWorker.js`.
- My APIs are under `http://localhost:8080/api/`. So same domain, just under a subfolder.
- I had set the `scope` option to `/api`, with the intention that `msw` would ignore all other requests.

Once I removed scope, it started working. It prints many warnings (since I had it set to `error`, trying to debug the situation), but my web app is now _functioning_.

If the way I have organized my paths combined with scope is an anti-pattern, it would probably be very helpful if the library would detect it and print a helpful instruction to my console. For people who know service workers, there may be something happening here that is obvious. But for someone new to them, and new to msw, I believe no prior knowledge should be assumed. I hope this helps.

**Comment by kettanaito** [comment]
The issue cannot be reproduced using these dependencies:

- `msw: 0.33.1`
- `storybook: 6.3.6`

I suspect that one of the issues we've tackled in the past has fixed this. I think it's #834, as MSW now explicitly bypasses Server-Sent Events issues by HMR. 

Please let me know if this is still an issue for you. Ensure that you're on the latest version of MSW and have _updated the worker script_, or set `msw.workerDirectory` in your package.json (recommended).
