### ISSUE TITLE
Request handlers find unrequired routes and warns about them

### ISSUE THREAD

**Issue by ghost** [mswjs/msw#790]
## Describe the bug
Bug in the console. MSW trying to find request handlers for unrequited routes in the public folder ( manifest.json, logo192.png, google font URL,  chrome-extension:fmkadmapgofadopljbjfkapdkoienihi/build/react_devtools_backend.js, )

## Environment

- `msw: 0.29.0`
- `nodejs: 14.15.3`
- `npm: 6.14.9`

> Please also provide your browser version.

## To Reproduce
1. Use MSW mock server in App
2. Start App with 'npm start' 
3. Open Dev Tools and look in the console
4. See an error

## Expected behavior
I just want an explanation of why are we mocking routes as manifest, CSS fonts, and things that aren't considered rest API routes inside the App? And if we can disable those unrequired request handlers to have a more "clean" console 

## Screenshots
![IFYRUN](https://user-images.githubusercontent.com/20955623/123062955-460f4000-d40d-11eb-8d1b-0186296014cf.png)

**Comment by kettanaito** [comment]
Hey, @stephyswe. 

Mock Service Worker captures _all_ requests that happen on the page and then sends them over to the client-side part of the library to figure out which should be mocked based on your request handlers. This means that even requests to images, static assets, and hor-reloading chunks are all captured, as they all are valid HTTP requests known to the worker.

Since the last release, the `onUnhandledRequest` option has been set to `"warn"` by default. That's why you see those warnings for requests that you never intended to mock. While this may be disruptive, it brings much more benefit statistically by warning people on typos, unintended and missing mocks. 

You can always disable those warnings by:

```js
worker.start({ onUnhandledRequest: 'bypass' })
```

> Learn more about [onUnhandledRequest](https://mswjs.io/docs/api/setup-worker/start#onunhandledrequest) option.

**Comment by alextrastero** [comment]
I handled image requests with the following:

```jsx
  worker.start({
    onUnhandledRequest(req) {
      if (req.destination !== 'image') {
        console.warn(
          'Found an unhandled %s request to %s',
          req.method,
          req.url.href,
        )
      }
  }});
```
