### ISSUE TITLE
use `networkError` message for throwing exception

### ISSUE THREAD

**Issue by mammadataei** [mswjs/msw#794]
According to the documentation should be possible to create a network error as response:

```js
rest.get('/books', (req, res, ctx) => {
  return res.networkError('Failed to connect')
})
```

but the message parameter is not used when throwing exceptions. The output message is just the default `Error: Network Error`.
Shouldn't use the provided message?

## Environment

- `msw: 0.30.0`
- `nodejs: 14.17.1`
-  jest test

**Comment by kettanaito** [comment]
Hey, @mammadataei. Thanks for reporting this. 

We're constructing a custom `NetworkError` class, which is a superset of the default `Error`, and providing the error message to that child class:

https://github.com/mswjs/msw/blob/1da34e4fef13e278043d65ad656875186ac84e90/src/utils/NetworkError.ts#L1-L6

You can later see that custom error message being available when network exceptions are thrown in Node.js:

https://github.com/mswjs/msw/blob/1da34e4fef13e278043d65ad656875186ac84e90/test/msw-api/res/network-error.node.test.ts#L13-L23

However, that won't be the case in a browser, and `rest.networkError()` will produce a generic `Failed to fetch` error, because that's how network errors are handled by `fetch` (assuming you're using `window.fetch`). 

It's worth mentioning that each request client may handle such errors differently. For instance, `axios` disregards the original network error message and uses its own. 

Let me know if I've missed something, or you've spotted an issue in the library's code. Thank you.

**Comment by mammadataei** [comment]
Hi @kettanaito, Thanks for the detailed description. It seems to be an issue with Axios.
