### ISSUE TITLE
req.params mismatching non param string

### ISSUE THREAD

**Issue by periabyte** [mswjs/msw#814]
## Environment

| Name | Version |
| ---- | ------- |
| msw  | 0.31.0   |
| node | v14.17.3     |
| OS   | MacOS     |

## Request handlers
```js
import { setupServer } from 'msw/node'
import { rest } from 'msw'

const retreiveBlogCategory = rest.get(
	`${API_URL}/blog-categories/:id`,
	(req, res, ctx) => {
		const { id } = req.params;

		return res(
			ctx.json({
				id,
			}),
		);
	},
);

const countBlogCategories = rest.get(
	`${API_URL}/blog-categories/count`,
	(req, res, ctx) => {
		return res(ctx.body(1));
	},
);


const server = setupServer(
  retreiveBlogCategory,
  countBlogCategories
)

server.listen()
```

## Actual request

```js
// retrieving a blog category
axios.get(`${API_URL}/blog-categories/1`).then((res) => res.json())

// retrieving a blog categories count
axios.get(`${API_URL}/blog-categories/count`).then((res) => res.json())
```

## Current behavior

```
    // count response
    Expected: 1
    Received: {"id": "count"}
```

## Expected behavior

```
    // count response
    Expected: 1
    Received: 1
```

**Comment by kettanaito** [comment]
Hey, @periabyte.

The behavior you're experiencing is expected: you've got a request URL that matches _both_ of the defined routes:

```
Given: /blog-categories/count
  - /blog-categories/:id (id: "count")
  - /blog-categories/count
```

This would also be the behavior on the server given the same routes unless you have an API to validate the path parameter type before matching. MSW doesn't do that, as this is redundant. MSW takes your request URL and finds the first handle that matches it. This lookup process is sensitive to the handler definition order. 


You can achieve your expected behavior by controlling the order in which those handlers are defined. 

I always recommend putting the dynamic paths _last_ in the list of paths that would match:

```js
rest.get(`${API_URL}/blog-categories/count`, resolver)
rest.get(`${API_URL}/blog-categories/:id`, resolver)
```
