### ISSUE TITLE
"Unsupported platform for fsevents" when installing (Ubuntu)

### ISSUE THREAD

**Issue by nibble0101** [mswjs/msw#816]
I am not sure whether this is an issue related to msw but when I run `npm i msw --save-dev` in my `create-react-app` project, I get the following error. I am using ubuntu.
```js
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for fsevents@2.3.1: wanted {"os":"darwin"} (current: {"os":"linux","arch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  undefined
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mawa/.npm/_logs/2021-07-17T14_53_18_190Z-debug.log
```

**Comment by kettanaito** [comment]
Hey, @nibble0101. 

Here's an `fsevents` dependency graph for MSW:

```diff
$ npm ls fsevents

 msw@0.32.2
 ├─┬ chokidar@3.5.1
+│ └── fsevents@2.3.2 
 ├─┬ jest@26.6.3
 │ └─┬ @jest/core@26.6.3
 │   └─┬ jest-haste-map@26.6.2
+│     └── fsevents@2.3.2  deduped 
 ├─┬ rollup@2.53.1
+│ └── fsevents@2.3.2  deduped
 └─┬ webpack-dev-server@3.11.2
   └─┬ chokidar@3.4.1 invalid
+    └── fsevents@2.1.3  extraneous
```

None of those dependencies are installed when installing MSW. The error you're seeing is likely caused by another, unrelated package. NPM can touch other dependencies while you're installing something, and I think that's why you see this error. 

I can recommend:

- Inspecting what other tools depend on `fsevents` in your project;
- Ensuring you're using the latest version of `npm` and a stable version of `node`;
- Try re-installing dependencies.
- Try installing some other dependency, see if the error is still there.

If nothing from the above helps, consider raising an issue in the [`fsevents`](https://github.com/fsevents/fsevents) repository and get some help from them. Search in the existing issues before asking.

**Comment by nibble0101** [comment]
Thanks @kettanaito 

I don't know whether it is the recommended way  but I fixed it as described [here on SO](https://stackoverflow.com/a/66385743/10855360).
