### ISSUE TITLE
[React Native] Regression in MSW 0.32.1 and above

### ISSUE THREAD

**Issue by taylorkline** [mswjs/msw#827]
## Describe the bug

Since MSW 0.32.1, `listen()` fails because the environment is not Node.js.

## Environment

- `msw: 0.32.1 & 0.32.2`

## Screenshots

![Simulator Screen Shot - iPhone 11 Pro Max - 2021-07-22 at 18 21 28](https://user-images.githubusercontent.com/2641739/126720779-a20cdc8b-d53c-4222-92d2-556fef883305.png)

**Comment by kettanaito** [comment]
Hey, @taylorkline. Thank you for reporting this.

We've migrated to use a standalone `is-node-process` package, which, apparently, produces a false negative result when run in React Native. The lack of testing in React Native is on my part, as I cannot run it locally due to some xcode issues.

I will provide a fix that will take `navigator.product` into account as it used to do previously: 

https://github.com/mswjs/msw/blob/8fb885faea504a3917491a639fd347ab748b4757/src/utils/internal/isNodeProcess.ts#L11-L17

**Comment by kettanaito** [comment]
@taylorkline, could you please update to 0.32.3 and let us know if the issue is gone?

**Comment by taylorkline** [comment]
Thank you. Will be able to do that on Tuesday.

**Comment by taylorkline** [comment]
@kettanaito yes, thanks, the issue is resolved in both 0.32.3 and 0.33.0.

**Comment by kettanaito** [comment]
Glad to hear that! Thank you for reporting it, @taylorkline.
