### ISSUE TITLE
onUnhandledRequest: throw error should fail test

### ISSUE THREAD

**Issue by ryumy97** [mswjs/msw#855]
**Is your feature request related to a problem? Please describe.**
When testing components, most of the API responses are required to be mocked which means that in most cases, the test should not continue without mocking them and should fail them immediately

**Describe the solution you'd like**
If an error is thrown in the functional implementation on `onUnhandledRequest` option, the test should fail.

If we specify:
```js
server.listen({
    onUnhandledRequest: (req) => {
        if(NOT_VALID) { //if req is something not expected,
            throw new Error("any error"); // throw error.
        }
    }
})
```

In test
```js
it('calls an endpoint', () => { 
  const res = await post('some/endpoints');  //Should fail here before reaching assertion
  
  expect(res.status).toBe(200);
})
```

The error thrown is going to fail the single test run, but not the whole process.

**Describe alternatives you've considered**
n/a

**Additional context**
#539

**Comment by kettanaito** [comment]
Hey, @ryumy97. Thank you for raising this and for referencing #539 as the related issue.

I think this is a valid suggestion and I was able to implement the following behavior:

<img width="1948" alt="Screen Shot 2021-08-09 at 11 47 06" src="https://user-images.githubusercontent.com/14984911/128688140-05c0eb2d-34ab-4560-8f39-6b66c87a09c1.png">

What the change above does is:

- Preserves the unhandled request error message because it's too verbose to be used as the request failure reason.
- Throws an exception, which halts the request processing and propagates that exception to the request client call.

I believe this would be the correct behavior. Will open a pull request once I have time. 

## Context

- [This](https://github.com/mswjs/interceptors/blob/ab7068666337d692a639184e5e1b90114f432707/src/interceptors/ClientRequest/createClientRequestOverride.ts#L192-L199) is how thrown exceptions propagate to the request client in Node.js

**Comment by ryumy97** [comment]
Thanks a lot!!! @kettanaito
