### ISSUE TITLE
on('request:match', (req) => {}) Does not get cleaned up

### ISSUE THREAD

**Issue by eddiemoore** [mswjs/msw#858]
## Describe the bug
I'm using `.on('request:match', (req) => {})` in tests to make sure variables are getting send correctly in the request, however is seems that if I have more than 1 across different tests then they start to fail. I have this in my setupTests file:
```typescript
beforeAll(() => server.listen({ onUnhandledRequest: 'error' }))
afterAll(() => server.close())
afterEach(() => server.resetHandlers())
```
It's like the `resetHandlers()` doesn't reset the `server.on`.

As soon as I comment out the `on()` section then the tests all pass.

## Environment

- `msw: 0.33.0`
- `nodejs: 14.17.3`
- `npm: 6.14.13`

## To Reproduce
1. listen for `.on('request:match')` in multiple tests.
2. watch the tests fail

## Expected behavior
Expect all tests to pass with `.on('request:match')` in multiple tests.

**Comment by kettanaito** [comment]
Hey, @eddiemoore. Thank you for reporting this!

This is an issue on the library's side. We aren't removing the listeners on the shared `emitter` instance when calling `resetHandlers`:

https://github.com/mswjs/msw/blob/99646b9a5f80ce4f205afc4c1e080f3c78bd0fef/src/node/createSetupServer.ts#L110-L115

https://github.com/mswjs/msw/blob/99646b9a5f80ce4f205afc4c1e080f3c78bd0fef/src/setupWorker/setupWorker.ts#L172-L177

I believe the fix is a matter of calling `emitter.removeAllListeners()` and `context.emitter.removeAllListeners()` in those two referenced places respectively.

Please, would you be interested in opening a pull request with a fix?
