### ISSUE TITLE
Consider adding rest.use handler

### ISSUE THREAD

**Issue by Arseniyboss** [mswjs/msw#893]
**Is your feature request related to a problem? Please describe.**

It's not a problem 

**Describe the solution you'd like**

```js
rest.use("/api/products", controller)
```

**Describe alternatives you've considered**

No alternatives

**Additional context**

rest.use allows not to specify the actual api methods and allow to use controller for the same url regardless of method.

**Comment by kettanaito** [comment]
This is a good idea. I was previously reluctant about this but it seems that catching all requests (regardless of the method) can be practical (i.e. when implementing proxies #886). 

I've opened a pull request (#896) that implements a new `rest.all()` API. I've decided to go with `.all()` vs `.use()` due to the semantic meaning ("all" reads "all methods", while "use" doesn't emphasize it has anything to do with methods).
