### ISSUE TITLE
mock service worker enabled in production dotenv inside nextjs template

### ISSUE THREAD

**Issue by Luccasoli** [mswjs/msw#894]
## Describe the bug
[Here](https://github.com/vercel/next.js/blob/canary/examples/with-msw/.env.production) you can see what I described in the title, and in the [documentation](https://mswjs.io/docs/getting-started/integrate/browser#start-worker) it is recommended to keep the service worker disabled to prevent incorrect information (mocked data) for the user.

I'm now starting to study msw, sorry if it's a false bug

## Environment
[Next js template with msw](https://github.com/vercel/next.js/tree/canary/examples/with-msw)

## Expected behavior
the value should be `disabled`

**Comment by Luccasoli** [comment]
If it is indeed an issue, I would love to resolve it! 😊

**Comment by Luccasoli** [comment]
I just noticed in the readme that this was intentional, but keeping it enabled in a production environment can't end up causing some first release issue?

![Captura de tela de 2021-08-29 21-05-21](https://user-images.githubusercontent.com/31039396/131269815-b09914e9-d2c7-4192-8e8d-f93971a7a3fd.png)

**Comment by kettanaito** [comment]
Hey, @Luccasoli. Thank you for raising this, it's a great question.

The documentation is correct: MSW should generally not be enabled in production, as there's very little reason for using mocks in production.

In the case of NextJS, the intention was to keep the environmental variable controlling MSW enabled so that you can witness MSW working in your preview builds. I don't think that keeping it enabled in the production `.env` is a good solution for that, though. 

I've raised the question of whether NextJS has a preview-specific `.env` file that we could utilize.
