### ISSUE TITLE
Improved error message for returning undefined

### ISSUE THREAD

**Issue by kentcdodds** [mswjs/msw#907]
I'm getting this error/warning:

```
[MSW] Expected a mocking resolver function to return a mocked response Object, but got: undefined. Original response is going to be used instead.
```

For this code in the photo I'm guessing.
1. Would be nice if the error mentioned the URL of the request that triggered the error so I'd be more sure where it's coming from
2. Would be nice if there were some way for me to silence the warning as it's intentional.

![image](https://user-images.githubusercontent.com/1500684/132927263-61e3ff38-b01e-4663-a9c2-839def5d7a17.png)

**Comment by kettanaito** [comment]
Hey, @kentcdodds. Thanks for transferring the issue here.

I've opened a pull request to add some crucial request handler info into the warning so it's easier to understand which handler causes it. As to disabling this warning, would it work for you if we disabled _all_ warnings in the production environment? If the main nuisance comes from the warnings polluting the stdout, then I don't think that's the solution.

**Comment by kettanaito** [comment]
I think that giving the end-developer controls over the internal logger isn't a good idea. I'd much more prefer using something like #676 for explicit request bypassing. That way the library would know when the bypass is intentional vs when it's an oversight (like the lack of the return statement). I think that's the right solution here.

**Comment by kentcdodds** [comment]
I agree
